import sys
import os

myDir = os.getcwd()
sys.path.append(myDir)
from wsgiref.validate import validator
from PyQt5 import QtCore, QtGui, QtWidgets
from Models.Product import Product
from Controllers.controlstockController import controlstockController
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import QRegExpValidator, QDoubleValidator, QValidator
from Database.Connection import connection


class Ui_controlDeStock(object):
    def __init__(self):
        self.controlstock_controller = controlstockController(self)
        self.productos = Product(connection())     
    def setupUi(self, controlDeStock):
        #Validador de input en int
        intValidator = QRegExpValidator(QRegExp(r'[0-9\s]+'))
        
        #Validador de input string
        stringValidator = QRegExpValidator(QRegExp(r'[a-zA-Z\s]+'))
        controlDeStock.setObjectName("controlDeStock")
        controlDeStock.resize(965, 683)
        controlDeStock.setStyleSheet("background-color: rgb(56, 213, 203);\n"
"background-color: rgb(0, 170, 255);")
        self.tabWidget = QtWidgets.QTabWidget(controlDeStock)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 931, 701))
        self.tabWidget.setStyleSheet("background-color: rgb(56, 213, 203);\n"
"background-color: rgb(0, 170, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.ProductosActivos = QtWidgets.QWidget()
        self.ProductosActivos.setObjectName("ProductosActivos")
        self.label = QtWidgets.QLabel(self.ProductosActivos)
        self.label.setGeometry(QtCore.QRect(370, 30, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.ProductosActivos)
        self.label_2.setGeometry(QtCore.QRect(90, 100, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.input_codigo = QtWidgets.QLineEdit(self.ProductosActivos)
        self.input_codigo.setGeometry(QtCore.QRect(90, 130, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_codigo.setFont(font)
        self.input_codigo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_codigo.setMaxLength(15)
        self.input_codigo.setObjectName("input_codigo")
        self.input_prod = QtWidgets.QLineEdit(self.ProductosActivos)
        self.input_prod.setGeometry(QtCore.QRect(260, 130, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_prod.setFont(font)
        self.input_prod.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_prod.setMaxLength(20)
        self.input_prod.setObjectName("input_prod")
        self.btn_buscar = QtWidgets.QPushButton(self.ProductosActivos)
        self.btn_buscar.setGeometry(QtCore.QRect(440, 130, 75, 21))
        self.btn_buscar.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.btn_buscar.setObjectName("btn_buscar")
        self.table_product = QtWidgets.QTableWidget(self.ProductosActivos)
        self.table_product.setEnabled(True)
        self.table_product.setGeometry(QtCore.QRect(90, 180, 740, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_product.sizePolicy().hasHeightForWidth())
        self.table_product.setSizePolicy(sizePolicy)
        self.table_product.setMinimumSize(QtCore.QSize(740, 350))
        self.table_product.setStyleSheet("background-color: rgb(172, 242, 255);")
        self.table_product.setMidLineWidth(1)
        self.table_product.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_product.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_product.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_product.setRowCount(20)
        self.table_product.setColumnCount(7)
        self.table_product.setObjectName("table_product")
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_product.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(6, item)
        self.table_product.horizontalHeader().setCascadingSectionResizes(False)
        self.table_product.horizontalHeader().setDefaultSectionSize(95)
        self.table_product.horizontalHeader().setMinimumSectionSize(30)
        self.table_product.verticalHeader().setDefaultSectionSize(30)
        self.label_3 = QtWidgets.QLabel(self.ProductosActivos)
        self.label_3.setGeometry(QtCore.QRect(260, 100, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btn_actualizar = QtWidgets.QPushButton(self.ProductosActivos)
        self.btn_actualizar.setGeometry(QtCore.QRect(310, 560, 121, 30))
        self.btn_actualizar.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_actualizar.setFont(font)
        self.btn_actualizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_actualizar.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.btn_actualizar.setObjectName("btn_actualizar")
        self.btn_volver = QtWidgets.QPushButton(self.ProductosActivos)
        self.btn_volver.setGeometry(QtCore.QRect(460, 560, 140, 30))
        self.btn_volver.setMinimumSize(QtCore.QSize(140, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_volver.setFont(font)
        self.btn_volver.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.btn_volver.setObjectName("btn_volver")
        self.btn_limpiar = QtWidgets.QPushButton(self.ProductosActivos)
        self.btn_limpiar.setGeometry(QtCore.QRect(530, 130, 75, 21))
        self.btn_limpiar.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.btn_limpiar.setObjectName("btn_limpiar")
        self.tabWidget.addTab(self.ProductosActivos, "")
        self.ProductosBajosStock = QtWidgets.QWidget()
        self.ProductosBajosStock.setObjectName("ProductosBajosStock")
        self.input_prod_2 = QtWidgets.QLineEdit(self.ProductosBajosStock)
        self.input_prod_2.setGeometry(QtCore.QRect(260, 130, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_prod_2.setFont(font)
        self.input_prod_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_prod_2.setMaxLength(20)
        self.input_prod_2.setObjectName("input_prod_2")
        self.label_4 = QtWidgets.QLabel(self.ProductosBajosStock)
        self.label_4.setGeometry(QtCore.QRect(90, 100, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.input_codigo_2 = QtWidgets.QLineEdit(self.ProductosBajosStock)
        self.input_codigo_2.setGeometry(QtCore.QRect(90, 130, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_codigo_2.setFont(font)
        self.input_codigo_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_codigo_2.setMaxLength(15)
        self.input_codigo_2.setObjectName("input_codigo_2")
        self.label_5 = QtWidgets.QLabel(self.ProductosBajosStock)
        self.label_5.setGeometry(QtCore.QRect(260, 100, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.ProductosBajosStock)
        self.label_6.setGeometry(QtCore.QRect(260, 30, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btn_buscar_2 = QtWidgets.QPushButton(self.ProductosBajosStock)
        self.btn_buscar_2.setGeometry(QtCore.QRect(440, 130, 75, 21))
        self.btn_buscar_2.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.btn_buscar_2.setObjectName("btn_buscar_2")
        self.btn_limpiar_2 = QtWidgets.QPushButton(self.ProductosBajosStock)
        self.btn_limpiar_2.setGeometry(QtCore.QRect(530, 130, 75, 21))
        self.btn_limpiar_2.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.btn_limpiar_2.setObjectName("btn_limpiar_2")
        self.btn_volver_2 = QtWidgets.QPushButton(self.ProductosBajosStock)
        self.btn_volver_2.setEnabled(True)
        self.btn_volver_2.setGeometry(QtCore.QRect(580, 560, 120, 30))
        self.btn_volver_2.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_volver_2.setFont(font)
        self.btn_volver_2.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.btn_volver_2.setObjectName("btn_volver_2")
        self.table_product_2 = QtWidgets.QTableWidget(self.ProductosBajosStock)
        self.table_product_2.setEnabled(True)
        self.table_product_2.setGeometry(QtCore.QRect(90, 180, 740, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_product_2.sizePolicy().hasHeightForWidth())
        self.table_product_2.setSizePolicy(sizePolicy)
        self.table_product_2.setMinimumSize(QtCore.QSize(740, 350))
        self.table_product_2.setStyleSheet("background-color: rgb(172, 242, 255);\n"
"background-color: rgb(255, 255, 127);")
        self.table_product_2.setMidLineWidth(1)
        self.table_product_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_product_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_product_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_product_2.setRowCount(20)
        self.table_product_2.setColumnCount(7)
        self.table_product_2.setObjectName("table_product_2")
        item = QtWidgets.QTableWidgetItem()
        self.table_product_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_product_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product_2.setHorizontalHeaderItem(6, item)
        self.table_product_2.horizontalHeader().setCascadingSectionResizes(False)
        self.table_product_2.horizontalHeader().setDefaultSectionSize(95)
        self.table_product_2.horizontalHeader().setMinimumSectionSize(30)
        self.table_product_2.verticalHeader().setDefaultSectionSize(30)
        self.btn_actualizar_2 = QtWidgets.QPushButton(self.ProductosBajosStock)
        self.btn_actualizar_2.setGeometry(QtCore.QRect(260, 560, 120, 30))
        self.btn_actualizar_2.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_actualizar_2.setFont(font)
        self.btn_actualizar_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_actualizar_2.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.btn_actualizar_2.setObjectName("btn_actualizar_2")
        self.btn_imprimir = QtWidgets.QPushButton(self.ProductosBajosStock)
        self.btn_imprimir.setEnabled(True)
        self.btn_imprimir.setGeometry(QtCore.QRect(420, 560, 120, 30))
        self.btn_imprimir.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_imprimir.setFont(font)
        self.btn_imprimir.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.btn_imprimir.setObjectName("btn_imprimir")
        self.tabWidget.addTab(self.ProductosBajosStock, "")

        self.retranslateUi(controlDeStock)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(controlDeStock)

        #Inputs con validadores
        self.input_codigo.setValidator(intValidator)
        self.input_codigo_2.setValidator(intValidator)

        self.completer_nameProd = QCompleter(self.productos.autoComplete()) 
        self.input_prod.setCompleter(self.completer_nameProd)

        self.completer_nameProd_2 = QCompleter(self.productos.autoComplete_3())
        self.input_prod_2.setCompleter(self.completer_nameProd_2)
        
        

        self.a = self.btn_actualizar.clicked.connect(lambda:self.controlstock_controller.listarStockActivos())
        
        self.c = self.btn_actualizar_2.clicked.connect(lambda:self.controlstock_controller.listarBajoStock())
        self.c = self.btn_imprimir.clicked.connect(lambda:self.controlstock_controller.imprimirLista())
        self.e = self.btn_buscar.clicked.connect(lambda:self.controlstock_controller.buscarStock(self.input_codigo.text(), self.input_prod.text()))
        self.e = self.btn_buscar_2.clicked.connect(lambda:self.controlstock_controller.buscarStockBajo(self.input_codigo_2.text(), self.input_prod_2.text()))
        self.e = self.btn_limpiar.clicked.connect(lambda:self.controlstock_controller.limpiar())
        self.e = self.btn_limpiar_2.clicked.connect(lambda:self.controlstock_controller.limpiar_2())
        self.p = self.btn_volver.clicked.connect(lambda:self.controlstock_controller.salir(controlDeStock))
        self.p = self.btn_volver_2.clicked.connect(lambda:self.controlstock_controller.salir(controlDeStock))
        #--------------------End Events---------------------------------

    def retranslateUi(self, controlDeStock):
        _translate = QtCore.QCoreApplication.translate
        controlDeStock.setWindowTitle(_translate("controlDeStock", "Control De Stock"))
        self.label.setText(_translate("controlDeStock", "Control de Stock"))
        self.label_2.setText(_translate("controlDeStock", "Codigo de Barras"))
        self.btn_buscar.setText(_translate("controlDeStock", "Buscar"))
        item = self.table_product.horizontalHeaderItem(0)
        item.setText(_translate("controlDeStock", "Cód. Producto"))
        item = self.table_product.horizontalHeaderItem(1)
        item.setText(_translate("controlDeStock", "Cód. de Barras"))
        item = self.table_product.horizontalHeaderItem(2)
        item.setText(_translate("controlDeStock", "Producto"))
        item = self.table_product.horizontalHeaderItem(3)
        item.setText(_translate("controlDeStock", "Marca"))
        item = self.table_product.horizontalHeaderItem(4)
        item.setText(_translate("controlDeStock", "Cant. en Stock"))
        item = self.table_product.horizontalHeaderItem(5)
        item.setText(_translate("controlDeStock", "Punto de Pedido"))
        item = self.table_product.horizontalHeaderItem(6)
        item.setText(_translate("controlDeStock", "Stock Min."))
        self.label_3.setText(_translate("controlDeStock", "Producto"))
        self.btn_actualizar.setText(_translate("controlDeStock", "Actualizar"))
        self.btn_volver.setText(_translate("controlDeStock", "Salir"))
        self.btn_limpiar.setText(_translate("controlDeStock", "Limpiar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ProductosActivos), _translate("controlDeStock", "Productos Activos"))
        self.label_4.setText(_translate("controlDeStock", "Codigo de Barras"))
        self.label_5.setText(_translate("controlDeStock", "Producto"))
        self.label_6.setText(_translate("controlDeStock", "Productos bajos en Stock"))
        self.btn_buscar_2.setText(_translate("controlDeStock", "Buscar"))
        self.btn_limpiar_2.setText(_translate("controlDeStock", "Limpiar"))
        self.btn_volver_2.setText(_translate("controlDeStock", "Salir"))
        item = self.table_product_2.horizontalHeaderItem(0)
        item.setText(_translate("controlDeStock", "Cód. Producto"))
        item = self.table_product_2.horizontalHeaderItem(1)
        item.setText(_translate("controlDeStock", "Cód. de Barras"))
        item = self.table_product_2.horizontalHeaderItem(2)
        item.setText(_translate("controlDeStock", "Producto"))
        item = self.table_product_2.horizontalHeaderItem(3)
        item.setText(_translate("controlDeStock", "Marca"))
        item = self.table_product_2.horizontalHeaderItem(4)
        item.setText(_translate("controlDeStock", "Cant. en Stock"))
        item = self.table_product_2.horizontalHeaderItem(5)
        item.setText(_translate("controlDeStock", "Punto de Pedido"))
        item = self.table_product_2.horizontalHeaderItem(6)
        item.setText(_translate("controlDeStock", "Stock Min."))
        self.btn_actualizar_2.setText(_translate("controlDeStock", "Actualizar"))
        self.btn_imprimir.setText(_translate("controlDeStock", "Imprimir lista"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ProductosBajosStock), _translate("controlDeStock", "Productos bajos en Stock"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    controlDeStock = QtWidgets.QWidget()
    ui = Ui_controlDeStock()
    ui.setupUi(controlDeStock)
    controlDeStock.show()
    sys.exit(app.exec_())
