import sys
import os

myDir = os.getcwd()
sys.path.append(myDir)
from wsgiref.validate import validator
from PyQt5 import QtCore, QtGui, QtWidgets
from modifBorrarProduct_ui import Ui_editEraseProduct
from createproduct_ui import Ui_CreateProduct
from Controllers.controlstockController import controlstockController
from PyQt5.QtWidgets import QApplication, QWidget, QLineEdit, QPlainTextEdit, QVBoxLayout
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator, QDoubleValidator, QValidator

class Ui_controlstock(object):
    def __init__(self):
        self.controlstock_controller = controlstockController(self)
    def setupUi(self, controlstock):
        #Validador de input en int
        intValidator = QRegExpValidator(QRegExp(r'[0-9\s]+'))
        
        #Validador de input string
        stringValidator = QRegExpValidator(QRegExp(r'[a-zA-Z\s]+'))
        controlstock.setObjectName("controlstock")
        controlstock.resize(1324, 683)
        controlstock.setStyleSheet("background-color: rgb(56, 213, 203);")
        self.btn_volver = QtWidgets.QPushButton(controlstock)
        self.btn_volver.setGeometry(QtCore.QRect(870, 630, 141, 31))
        self.btn_volver.setMinimumSize(QtCore.QSize(140, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_volver.setFont(font)
        self.btn_volver.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.btn_volver.setObjectName("btn_volver")
        self.table_product = QtWidgets.QTableWidget(controlstock)
        self.table_product.setEnabled(True)
        self.table_product.setGeometry(QtCore.QRect(30, 190, 1281, 351))
        self.table_product.setMinimumSize(QtCore.QSize(740, 350))
        self.table_product.setStyleSheet("background-color: rgb(172, 242, 255);")
        self.table_product.setMidLineWidth(1)
        self.table_product.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_product.setRowCount(20)
        self.table_product.setObjectName("table_product")
        self.table_product.setColumnCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_product.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_product.setHorizontalHeaderItem(11, item)
        self.table_product.horizontalHeader().setCascadingSectionResizes(False)
        self.table_product.horizontalHeader().setDefaultSectionSize(103)
        self.table_product.verticalHeader().setDefaultSectionSize(30)
        self.label = QtWidgets.QLabel(controlstock)
        self.label.setGeometry(QtCore.QRect(480, 30, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_actualizar = QtWidgets.QPushButton(controlstock)
        self.btn_actualizar.setGeometry(QtCore.QRect(445, 571, 100, 30))
        self.btn_actualizar.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_actualizar.setFont(font)
        self.btn_actualizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_actualizar.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.btn_actualizar.setObjectName("btn_actualizar")
        self.btn_create = QtWidgets.QPushButton(controlstock)
        self.btn_create.setGeometry(QtCore.QRect(625, 571, 100, 30))
        self.btn_create.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_create.setFont(font)
        self.btn_create.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_create.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.btn_create.setObjectName("btn_create")
        self.btn_delete = QtWidgets.QPushButton(controlstock)
        self.btn_delete.setGeometry(QtCore.QRect(805, 571, 100, 30))
        self.btn_delete.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_delete.setFont(font)
        self.btn_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_delete.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.btn_delete.setObjectName("btn_delete")
        self.input_codigo = QtWidgets.QLineEdit(controlstock)
        self.input_codigo.setGeometry(QtCore.QRect(50, 120, 161, 20))
        self.input_codigo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_codigo.setObjectName("input_codigo")
        self.label_2 = QtWidgets.QLabel(controlstock)
        self.label_2.setGeometry(QtCore.QRect(50, 95, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(controlstock)
        self.label_3.setGeometry(QtCore.QRect(240, 100, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.input_prod = QtWidgets.QLineEdit(controlstock)
        self.input_prod.setGeometry(QtCore.QRect(240, 120, 161, 20))
        self.input_prod.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_prod.setObjectName("input_prod")
        self.btn_buscar = QtWidgets.QPushButton(controlstock)
        self.btn_buscar.setGeometry(QtCore.QRect(410, 120, 75, 23))
        self.btn_buscar.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.btn_buscar.setObjectName("btn_buscar")

        self.retranslateUi(controlstock)
        QtCore.QMetaObject.connectSlotsByName(controlstock)

        #Inputs con validadores
        self.input_codigo.setValidator(intValidator)
        
        

        self.a = self.btn_actualizar.clicked.connect(lambda:self.controlstock_controller.updateProducs())
        self.c = self.btn_create.clicked.connect(lambda:self.controlstock_controller.openCreate(Ui_CreateProduct))
        
        self.d = self.btn_delete.clicked.connect(lambda:self.controlstock_controller.deleteProduct())
        self.p = self.btn_volver.clicked.connect(lambda:self.controlstock_controller.salir(controlstock))
        #--------------------End Events---------------------------------


    def retranslateUi(self, controlstock):
        _translate = QtCore.QCoreApplication.translate
        controlstock.setWindowTitle(_translate("controlstock", "Control de Stock"))
        self.btn_volver.setText(_translate("controlstock", "Volver al Menú"))
        item = self.table_product.horizontalHeaderItem(0)
        item.setText(_translate("controlstock", "CodProducto"))
        item = self.table_product.horizontalHeaderItem(1)
        item.setText(_translate("controlstock", "Código de Barras"))
        item = self.table_product.horizontalHeaderItem(2)
        item.setText(_translate("controlstock", "Producto"))
        item = self.table_product.horizontalHeaderItem(3)
        item.setText(_translate("controlstock", "Categoría"))
        item = self.table_product.horizontalHeaderItem(4)
        item.setText(_translate("controlstock", "Subcategoría"))
        item = self.table_product.horizontalHeaderItem(5)
        item.setText(_translate("controlstock", "Marca"))
        item = self.table_product.horizontalHeaderItem(6)
        item.setText(_translate("controlstock", "Tipo Unidad"))
        item = self.table_product.horizontalHeaderItem(7)
        item.setText(_translate("controlstock", "Unidad de Medida"))
        item = self.table_product.horizontalHeaderItem(8)
        item.setText(_translate("controlstock", "Cant. en Stock"))
        item = self.table_product.horizontalHeaderItem(9)
        item.setText(_translate("controlstock", "Punto de Pedido"))
        item = self.table_product.horizontalHeaderItem(10)
        item.setText(_translate("controlstock", "Costo de Compra"))
        item = self.table_product.horizontalHeaderItem(11)
        item.setText(_translate("controlstock", "Precio Venta"))
        self.label.setText(_translate("controlstock", "Control de Stock"))
        self.btn_actualizar.setText(_translate("controlstock", "Actualizar"))
        self.btn_create.setText(_translate("controlstock", "Crear"))
        self.btn_delete.setText(_translate("controlstock", "Eliminar"))
        self.label_2.setText(_translate("controlstock", "Codigo de Barras"))
        self.label_3.setText(_translate("controlstock", "Producto"))
        self.btn_buscar.setText(_translate("controlstock", "Buscar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    controlstock = QtWidgets.QWidget()
    ui = Ui_controlstock()
    ui.setupUi(controlstock)
    controlstock.show()
    sys.exit(app.exec_())
