import sys
import os
from wsgiref.validate import validator

from pymysql import STRING
myDir = os.getcwd()
sys.path.append(myDir)

from Controllers.detalleFacturaCompraController import detalleFacturaCompraController
from PyQt5 import QtCore, QtGui, QtWidgets
from Models.facturaCompra import FacturaCompra
from Models.Proveedores import *
from Database.Connection import connection


class Ui_detallefacturacompra(object):
    def __init__(self):
        self.detalleFacturaCompraController = detalleFacturaCompraController (self)
        self.factCompra = FacturaCompra(connection())


    def setupUi(self, detallefacturacompra):
        detallefacturacompra.setObjectName("detallefacturacompra")
        detallefacturacompra.resize(1020, 586)
        detallefacturacompra.setStyleSheet("QWidget{background-color:rgb(146,193,220)}\n"
"QGroupBox{background-color:lightgray}\n"
"QFrame{background-color:none}\n"
"QLabel{background-color:none}\n"
"QLineEdit{background-color:none}\n"
"QDateEdit{background-color:none}\n"
"QComboBox{background-color:none}\n"
"QTableWidget{background-color:black}\n"
"QPushButton{background-color:none}")
        self.groupBox_generales = QtWidgets.QGroupBox(detallefacturacompra)
        self.groupBox_generales.setGeometry(QtCore.QRect(10, 80, 1001, 181))
        self.groupBox_generales.setMinimumSize(QtCore.QSize(421, 1))
        self.groupBox_generales.setMaximumSize(QtCore.QSize(1200, 900))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_generales.setFont(font)
        self.groupBox_generales.setAutoFillBackground(False)
        self.groupBox_generales.setFlat(False)
        self.groupBox_generales.setObjectName("groupBox_generales")
        self.label_codProv = QtWidgets.QLabel(self.groupBox_generales)
        self.label_codProv.setGeometry(QtCore.QRect(15, 30, 151, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_codProv.setFont(font)
        self.label_codProv.setObjectName("label_codProv")
        self.input_facCompra = QtWidgets.QLineEdit(self.groupBox_generales)
        self.input_facCompra.setEnabled(False)
        self.input_facCompra.setGeometry(QtCore.QRect(185, 30, 260, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_facCompra.setFont(font)
        self.input_facCompra.setMaxLength(40)
        self.input_facCompra.setAlignment(QtCore.Qt.AlignCenter)
        self.input_facCompra.setObjectName("input_facCompra")
        self.label_nameProv = QtWidgets.QLabel(self.groupBox_generales)
        self.label_nameProv.setGeometry(QtCore.QRect(475, 30, 83, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_nameProv.setFont(font)
        self.label_nameProv.setObjectName("label_nameProv")
        self.input_nroFac = QtWidgets.QLineEdit(self.groupBox_generales)
        self.input_nroFac.setEnabled(False)
        self.input_nroFac.setGeometry(QtCore.QRect(185, 65, 260, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_nroFac.setFont(font)
        self.input_nroFac.setText("")
        self.input_nroFac.setMaxLength(12)
        self.input_nroFac.setAlignment(QtCore.Qt.AlignCenter)
        self.input_nroFac.setObjectName("input_nroFac")
        self.cuilOcuit = QtWidgets.QLabel(self.groupBox_generales)
        self.cuilOcuit.setGeometry(QtCore.QRect(15, 65, 116, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.cuilOcuit.setFont(font)
        self.cuilOcuit.setObjectName("cuilOcuit")
        self.label_ciudad = QtWidgets.QLabel(self.groupBox_generales)
        self.label_ciudad.setGeometry(QtCore.QRect(475, 100, 120, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_ciudad.setFont(font)
        self.label_ciudad.setObjectName("label_ciudad")
        self.label_ciudad_2 = QtWidgets.QLabel(self.groupBox_generales)
        self.label_ciudad_2.setGeometry(QtCore.QRect(15, 100, 133, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_ciudad_2.setFont(font)
        self.label_ciudad_2.setObjectName("label_ciudad_2")
        self.cuilOcuit_2 = QtWidgets.QLabel(self.groupBox_generales)
        self.cuilOcuit_2.setGeometry(QtCore.QRect(475, 65, 151, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.cuilOcuit_2.setFont(font)
        self.cuilOcuit_2.setObjectName("cuilOcuit_2")
        self.input_nroCuil = QtWidgets.QLineEdit(self.groupBox_generales)
        self.input_nroCuil.setEnabled(False)
        self.input_nroCuil.setGeometry(QtCore.QRect(645, 65, 291, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_nroCuil.setFont(font)
        self.input_nroCuil.setText("")
        self.input_nroCuil.setMaxLength(12)
        self.input_nroCuil.setAlignment(QtCore.Qt.AlignCenter)
        self.input_nroCuil.setObjectName("input_nroCuil")
        self.input_provFact = QtWidgets.QLineEdit(self.groupBox_generales)
        self.input_provFact.setEnabled(False)
        self.input_provFact.setGeometry(QtCore.QRect(645, 30, 291, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_provFact.setFont(font)
        self.input_provFact.setText("")
        self.input_provFact.setMaxLength(40)
        self.input_provFact.setAlignment(QtCore.Qt.AlignCenter)
        self.input_provFact.setObjectName("input_provFact")
        self.input_tipoCompra = QtWidgets.QLineEdit(self.groupBox_generales)
        self.input_tipoCompra.setEnabled(False)
        self.input_tipoCompra.setGeometry(QtCore.QRect(645, 100, 291, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_tipoCompra.setFont(font)
        self.input_tipoCompra.setText("")
        self.input_tipoCompra.setMaxLength(40)
        self.input_tipoCompra.setAlignment(QtCore.Qt.AlignCenter)
        self.input_tipoCompra.setObjectName("input_tipoCompra")
        self.input_fechaEmision = QtWidgets.QLineEdit(self.groupBox_generales)
        self.input_fechaEmision.setEnabled(False)
        self.input_fechaEmision.setGeometry(QtCore.QRect(185, 100, 260, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_fechaEmision.setFont(font)
        self.input_fechaEmision.setText("")
        self.input_fechaEmision.setMaxLength(12)
        self.input_fechaEmision.setAlignment(QtCore.Qt.AlignCenter)
        self.input_fechaEmision.setObjectName("input_fechaEmision")
        self.input_fechaEmision_2 = QtWidgets.QLineEdit(self.groupBox_generales)
        self.input_fechaEmision_2.setEnabled(False)
        self.input_fechaEmision_2.setGeometry(QtCore.QRect(185, 135, 260, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_fechaEmision_2.setFont(font)
        self.input_fechaEmision_2.setText("")
        self.input_fechaEmision_2.setMaxLength(12)
        self.input_fechaEmision_2.setAlignment(QtCore.Qt.AlignCenter)
        self.input_fechaEmision_2.setObjectName("input_fechaEmision_2")
        self.label_ciudad_3 = QtWidgets.QLabel(self.groupBox_generales)
        self.label_ciudad_3.setGeometry(QtCore.QRect(15, 135, 133, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_ciudad_3.setFont(font)
        self.label_ciudad_3.setObjectName("label_ciudad_3")
        self.boton_salir = QtWidgets.QPushButton(detallefacturacompra)
        self.boton_salir.setGeometry(QtCore.QRect(920, 550, 91, 27))
        self.boton_salir.setMaximumSize(QtCore.QSize(200, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.boton_salir.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_salir.setFont(font)
        self.boton_salir.setObjectName("boton_salir")
        self.label = QtWidgets.QLabel(detallefacturacompra)
        self.label.setGeometry(QtCore.QRect(10, 20, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox_datosContacto = QtWidgets.QGroupBox(detallefacturacompra)
        self.groupBox_datosContacto.setGeometry(QtCore.QRect(10, 270, 1000, 261))
        self.groupBox_datosContacto.setMinimumSize(QtCore.QSize(421, 211))
        self.groupBox_datosContacto.setMaximumSize(QtCore.QSize(1000, 900))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_datosContacto.setFont(font)
        self.groupBox_datosContacto.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_datosContacto.setAutoFillBackground(False)
        self.groupBox_datosContacto.setObjectName("groupBox_datosContacto")
        self.table_venta = QtWidgets.QTableWidget(self.groupBox_datosContacto)
        self.table_venta.setGeometry(QtCore.QRect(15, 30, 641, 141))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.table_venta.setFont(font)
        self.table_venta.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.table_venta.setStyleSheet("QTableWidget{background-color:rgb(187,235,255)}")
        self.table_venta.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.table_venta.setAutoScroll(True)
        self.table_venta.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_venta.setTabKeyNavigation(False)
        self.table_venta.setProperty("showDropIndicator", False)
        self.table_venta.setDragDropOverwriteMode(False)
        self.table_venta.setObjectName("table_venta")
        self.table_venta.setColumnCount(6)
        self.table_venta.setRowCount(50)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(40, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(41, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(42, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(43, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(44, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(45, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(46, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(47, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(48, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(49, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_venta.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(True)
        item.setFont(font)
        self.table_venta.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_venta.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_venta.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        self.table_venta.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setItem(0, 3, item)
        self.precio_2 = QtWidgets.QLabel(self.groupBox_datosContacto)
        self.precio_2.setGeometry(QtCore.QRect(480, 210, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.precio_2.setFont(font)
        self.precio_2.setObjectName("precio_2")
        self.input_iva = QtWidgets.QLineEdit(self.groupBox_datosContacto)
        self.input_iva.setEnabled(False)
        self.input_iva.setGeometry(QtCore.QRect(560, 210, 131, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_iva.setFont(font)
        self.input_iva.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_iva.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_iva.setText("")
        self.input_iva.setMaxLength(5)
        self.input_iva.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_iva.setObjectName("input_iva")
        self.input_subtotal = QtWidgets.QLineEdit(self.groupBox_datosContacto)
        self.input_subtotal.setEnabled(False)
        self.input_subtotal.setGeometry(QtCore.QRect(85, 210, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_subtotal.setFont(font)
        self.input_subtotal.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_subtotal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_subtotal.setText("")
        self.input_subtotal.setMaxLength(5)
        self.input_subtotal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_subtotal.setObjectName("input_subtotal")
        self.precio_3 = QtWidgets.QLabel(self.groupBox_datosContacto)
        self.precio_3.setGeometry(QtCore.QRect(10, 210, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.precio_3.setFont(font)
        self.precio_3.setObjectName("precio_3")
        self.precio_4 = QtWidgets.QLabel(self.groupBox_datosContacto)
        self.precio_4.setGeometry(QtCore.QRect(240, 210, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.precio_4.setFont(font)
        self.precio_4.setObjectName("precio_4")
        self.input_descuento_2 = QtWidgets.QLineEdit(self.groupBox_datosContacto)
        self.input_descuento_2.setEnabled(False)
        self.input_descuento_2.setGeometry(QtCore.QRect(330, 210, 131, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_descuento_2.setFont(font)
        self.input_descuento_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_descuento_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_descuento_2.setText("")
        self.input_descuento_2.setMaxLength(5)
        self.input_descuento_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_descuento_2.setObjectName("input_descuento_2")
        self.input_importe = QtWidgets.QLineEdit(self.groupBox_datosContacto)
        self.input_importe.setEnabled(False)
        self.input_importe.setGeometry(QtCore.QRect(840, 210, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_importe.setFont(font)
        self.input_importe.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_importe.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_importe.setText("")
        self.input_importe.setMaxLength(5)
        self.input_importe.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_importe.setObjectName("input_importe")
        self.precio_5 = QtWidgets.QLabel(self.groupBox_datosContacto)
        self.precio_5.setGeometry(QtCore.QRect(705, 210, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.precio_5.setFont(font)
        self.precio_5.setObjectName("precio_5")
        self.line = QtWidgets.QFrame(self.groupBox_datosContacto)
        self.line.setGeometry(QtCore.QRect(0, 170, 1001, 41))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(detallefacturacompra)
        QtCore.QMetaObject.connectSlotsByName(detallefacturacompra)

        #
    #--------------------Events------------------------------------------------
    def displayInfo(self):
        self.show() 
    #--------------------End Events--------------------------------------------

    def retranslateUi(self, detallefacturacompra):
        _translate = QtCore.QCoreApplication.translate
        detallefacturacompra.setWindowTitle(_translate("detallefacturacompra", "Detalle Factura de Compra"))
        self.groupBox_generales.setTitle(_translate("detallefacturacompra", "Datos"))
        self.label_codProv.setText(_translate("detallefacturacompra", "<html><head/><body><p>Tipo de Documento:</p></body></html>"))
        self.input_facCompra.setText(_translate("detallefacturacompra", "Factura de Compra"))
        self.input_facCompra.setPlaceholderText(_translate("detallefacturacompra", "Apellido y Nombre Proveedor"))
        self.label_nameProv.setText(_translate("detallefacturacompra", "<html><head/><body><p>Proveedor:</p></body></html>"))
        self.input_nroFac.setPlaceholderText(_translate("detallefacturacompra", "Nro de Factura"))
        self.cuilOcuit.setText(_translate("detallefacturacompra", "<html><head/><body><p>Nro de Factura:</p></body></html>"))
        self.label_ciudad.setText(_translate("detallefacturacompra", "<html><head/><body><p>Tipo de Compra:</p><p><br/></p></body></html>"))
        self.label_ciudad_2.setText(_translate("detallefacturacompra", "<html><head/><body><p>Fecha de Emisión:</p><p><br/></p></body></html>"))
        self.cuilOcuit_2.setText(_translate("detallefacturacompra", "<html><head/><body><p>Nro de CUIL o CUIT:</p></body></html>"))
        self.input_nroCuil.setPlaceholderText(_translate("detallefacturacompra", "Nro de CUIL o CUIT"))
        self.input_provFact.setPlaceholderText(_translate("detallefacturacompra", "Proveedor"))
        self.input_tipoCompra.setPlaceholderText(_translate("detallefacturacompra", "Tipo de Compra"))
        self.input_fechaEmision.setPlaceholderText(_translate("detallefacturacompra", "Fecha de Emisión"))
        self.input_fechaEmision_2.setPlaceholderText(_translate("detallefacturacompra", "Fecha de Carga"))
        self.label_ciudad_3.setText(_translate("detallefacturacompra", "<html><head/><body><p>Fecha de Carga:</p><p><br/></p></body></html>"))
        self.boton_salir.setText(_translate("detallefacturacompra", "Salir"))
        self.label.setText(_translate("detallefacturacompra", "Factura de Compra"))
        self.groupBox_datosContacto.setTitle(_translate("detallefacturacompra", "Detalle"))
        item = self.table_venta.verticalHeaderItem(0)
        item.setText(_translate("detallefacturacompra", "1"))
        item = self.table_venta.verticalHeaderItem(1)
        item.setText(_translate("detallefacturacompra", "2"))
        item = self.table_venta.verticalHeaderItem(2)
        item.setText(_translate("detallefacturacompra", "3"))
        item = self.table_venta.verticalHeaderItem(3)
        item.setText(_translate("detallefacturacompra", "4"))
        item = self.table_venta.verticalHeaderItem(4)
        item.setText(_translate("detallefacturacompra", "5"))
        item = self.table_venta.verticalHeaderItem(5)
        item.setText(_translate("detallefacturacompra", "6"))
        item = self.table_venta.verticalHeaderItem(6)
        item.setText(_translate("detallefacturacompra", "7"))
        item = self.table_venta.verticalHeaderItem(7)
        item.setText(_translate("detallefacturacompra", "8"))
        item = self.table_venta.verticalHeaderItem(8)
        item.setText(_translate("detallefacturacompra", "9"))
        item = self.table_venta.verticalHeaderItem(9)
        item.setText(_translate("detallefacturacompra", "10"))
        item = self.table_venta.verticalHeaderItem(10)
        item.setText(_translate("detallefacturacompra", "11"))
        item = self.table_venta.verticalHeaderItem(11)
        item.setText(_translate("detallefacturacompra", "12"))
        item = self.table_venta.verticalHeaderItem(12)
        item.setText(_translate("detallefacturacompra", "13"))
        item = self.table_venta.verticalHeaderItem(13)
        item.setText(_translate("detallefacturacompra", "14"))
        item = self.table_venta.verticalHeaderItem(14)
        item.setText(_translate("detallefacturacompra", "15"))
        item = self.table_venta.verticalHeaderItem(15)
        item.setText(_translate("detallefacturacompra", "16"))
        item = self.table_venta.verticalHeaderItem(16)
        item.setText(_translate("detallefacturacompra", "17"))
        item = self.table_venta.verticalHeaderItem(17)
        item.setText(_translate("detallefacturacompra", "18"))
        item = self.table_venta.verticalHeaderItem(18)
        item.setText(_translate("detallefacturacompra", "19"))
        item = self.table_venta.verticalHeaderItem(19)
        item.setText(_translate("detallefacturacompra", "20"))
        item = self.table_venta.verticalHeaderItem(20)
        item.setText(_translate("detallefacturacompra", "21"))
        item = self.table_venta.verticalHeaderItem(21)
        item.setText(_translate("detallefacturacompra", "22"))
        item = self.table_venta.verticalHeaderItem(22)
        item.setText(_translate("detallefacturacompra", "23"))
        item = self.table_venta.verticalHeaderItem(23)
        item.setText(_translate("detallefacturacompra", "24"))
        item = self.table_venta.verticalHeaderItem(24)
        item.setText(_translate("detallefacturacompra", "25"))
        item = self.table_venta.verticalHeaderItem(25)
        item.setText(_translate("detallefacturacompra", "26"))
        item = self.table_venta.verticalHeaderItem(26)
        item.setText(_translate("detallefacturacompra", "27"))
        item = self.table_venta.verticalHeaderItem(27)
        item.setText(_translate("detallefacturacompra", "28"))
        item = self.table_venta.verticalHeaderItem(28)
        item.setText(_translate("detallefacturacompra", "29"))
        item = self.table_venta.verticalHeaderItem(29)
        item.setText(_translate("detallefacturacompra", "30"))
        item = self.table_venta.verticalHeaderItem(30)
        item.setText(_translate("detallefacturacompra", "31"))
        item = self.table_venta.verticalHeaderItem(31)
        item.setText(_translate("detallefacturacompra", "32"))
        item = self.table_venta.verticalHeaderItem(32)
        item.setText(_translate("detallefacturacompra", "33"))
        item = self.table_venta.verticalHeaderItem(33)
        item.setText(_translate("detallefacturacompra", "34"))
        item = self.table_venta.verticalHeaderItem(34)
        item.setText(_translate("detallefacturacompra", "35"))
        item = self.table_venta.verticalHeaderItem(35)
        item.setText(_translate("detallefacturacompra", "36"))
        item = self.table_venta.verticalHeaderItem(36)
        item.setText(_translate("detallefacturacompra", "37"))
        item = self.table_venta.verticalHeaderItem(37)
        item.setText(_translate("detallefacturacompra", "38"))
        item = self.table_venta.verticalHeaderItem(38)
        item.setText(_translate("detallefacturacompra", "39"))
        item = self.table_venta.verticalHeaderItem(39)
        item.setText(_translate("detallefacturacompra", "40"))
        item = self.table_venta.verticalHeaderItem(40)
        item.setText(_translate("detallefacturacompra", "41"))
        item = self.table_venta.verticalHeaderItem(41)
        item.setText(_translate("detallefacturacompra", "42"))
        item = self.table_venta.verticalHeaderItem(42)
        item.setText(_translate("detallefacturacompra", "43"))
        item = self.table_venta.verticalHeaderItem(43)
        item.setText(_translate("detallefacturacompra", "44"))
        item = self.table_venta.verticalHeaderItem(44)
        item.setText(_translate("detallefacturacompra", "45"))
        item = self.table_venta.verticalHeaderItem(45)
        item.setText(_translate("detallefacturacompra", "46"))
        item = self.table_venta.verticalHeaderItem(46)
        item.setText(_translate("detallefacturacompra", "47"))
        item = self.table_venta.verticalHeaderItem(47)
        item.setText(_translate("detallefacturacompra", "48"))
        item = self.table_venta.verticalHeaderItem(48)
        item.setText(_translate("detallefacturacompra", "49"))
        item = self.table_venta.verticalHeaderItem(49)
        item.setText(_translate("detallefacturacompra", "50"))
        item = self.table_venta.horizontalHeaderItem(0)
        item.setText(_translate("detallefacturacompra", "Código Prod."))
        item = self.table_venta.horizontalHeaderItem(1)
        item.setText(_translate("detallefacturacompra", "Cód. de Barras"))
        item = self.table_venta.horizontalHeaderItem(2)
        item.setText(_translate("detallefacturacompra", "Producto"))
        item = self.table_venta.horizontalHeaderItem(3)
        item.setText(_translate("detallefacturacompra", "Cantidad"))
        item = self.table_venta.horizontalHeaderItem(4)
        item.setText(_translate("detallefacturacompra", "Precio Unit."))
        item = self.table_venta.horizontalHeaderItem(5)
        item.setText(_translate("detallefacturacompra", "Subtotal"))
        __sortingEnabled = self.table_venta.isSortingEnabled()
        self.table_venta.setSortingEnabled(False)
        self.table_venta.setSortingEnabled(__sortingEnabled)
        self.precio_2.setText(_translate("detallefacturacompra", "IVA 21%:"))
        self.precio_3.setText(_translate("detallefacturacompra", "Subtotal:"))
        self.precio_4.setText(_translate("detallefacturacompra", "Descuento:"))
        self.precio_5.setText(_translate("detallefacturacompra", "IMPORTE TOTAL:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    detallefacturacompra = QtWidgets.QWidget()
    ui = Ui_detallefacturacompra()
    ui.setupUi(detallefacturacompra)
    detallefacturacompra.show()
    sys.exit(app.exec_())
