import sys
import os
from tkinter.tix import Form
from wsgiref.validate import validator
from pymysql import STRING

myDir = os.getcwd()
sys.path.append(myDir)

from PyQt5 import QtCore, QtGui, QtWidgets
from Controllers.facturaCompraController import facturaCompraController
from Controllers.menuprincipalController import menuprincipalController
from Database.Connection import connection
from Models.Product import Product
from Models.Proveedores import *
from createproduct_ui import Ui_CreateProduct
from proveedores_ui import Ui_Proveedores
from listaDeProductos_ui import Ui_listaDeProductos


class Ui_FacturaDeCompra(object):
    def __init__(self):
        self.facturaCompraController = facturaCompraController(self)
        self.product = Product(connection())
        self.proveedor = Proveedor(connection())
        self.menuPrincipal= menuprincipalController(self)

    def timer(self):
        self.typing_timer = QtCore.QTimer()
        self.typing_timer.setSingleShot(True)
        self.typing_timer.timeout.connect(self.cambiarNombreProd)
        self.input_codprod.textChanged.connect(self.timerEscribiendo)

    def timerEscribiendo(self):
        #Se espera 200ms antes de chequear si hubo cambios
        self.typing_timer.start(200)

    def cambiarNombreProd(self):
        codbarra = self.input_codprod.text()
        nombre = self.input_provFact.text()
        nombreProd = self.product.actualizarNombreProd(codbarra,nombre)
        try:
            self.input_nombreProd.setText(str(nombreProd[0]))
        except:
            pass

    def setupUi(self, FacturaDeCompra):
        FacturaDeCompra.setObjectName("FacturaDeCompra")
        FacturaDeCompra.resize(1020, 640)
        FacturaDeCompra.setStyleSheet("QWidget{background-color:rgb(146,193,220)}\n"
"QGroupBox{background-color:lightgray}\n"
"QFrame{background-color:none}\n"
"QLabel{background-color:none}\n"
"QLineEdit{background-color:none}\n"
"QDateEdit{background-color:none}\n"
"QComboBox{background-color:none}\n"
"QTableWidget{background-color:black}\n"
"QPushButton{background-color:none}")
        self.label = QtWidgets.QLabel(FacturaDeCompra)
        self.label.setGeometry(QtCore.QRect(10, 0, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox_datosContacto = QtWidgets.QGroupBox(FacturaDeCompra)
        self.groupBox_datosContacto.setGeometry(QtCore.QRect(10, 210, 1000, 351))
        self.groupBox_datosContacto.setMinimumSize(QtCore.QSize(421, 211))
        self.groupBox_datosContacto.setMaximumSize(QtCore.QSize(1000, 900))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_datosContacto.setFont(font)
        self.groupBox_datosContacto.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_datosContacto.setAutoFillBackground(False)
        self.groupBox_datosContacto.setObjectName("groupBox_datosContacto")
        self.table_venta = QtWidgets.QTableWidget(self.groupBox_datosContacto)
        self.table_venta.setGeometry(QtCore.QRect(15, 70, 641, 141))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.table_venta.setFont(font)
        self.table_venta.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.table_venta.setStyleSheet("QTableWidget{background-color:rgb(187,235,255)}")
        self.table_venta.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.table_venta.setAutoScroll(True)
        self.table_venta.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_venta.setTabKeyNavigation(False)
        self.table_venta.setProperty("showDropIndicator", False)
        self.table_venta.setDragDropOverwriteMode(False)
        self.table_venta.setObjectName("table_venta")
        self.table_venta.setColumnCount(6)
        self.table_venta.setRowCount(50)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(40, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(41, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(42, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(43, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(44, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(45, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(46, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(47, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(48, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setVerticalHeaderItem(49, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_venta.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(True)
        item.setFont(font)
        self.table_venta.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_venta.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_venta.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        self.table_venta.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_venta.setItem(0, 3, item)
        self.codprod = QtWidgets.QLabel(self.groupBox_datosContacto)
        self.codprod.setGeometry(QtCore.QRect(15, 30, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.codprod.setFont(font)
        self.codprod.setObjectName("codprod")
        self.input_cantidad = QtWidgets.QLineEdit(self.groupBox_datosContacto)
        self.input_cantidad.setGeometry(QtCore.QRect(600, 30, 91, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_cantidad.setFont(font)
        self.input_cantidad.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_cantidad.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_cantidad.setText("")
        self.input_cantidad.setMaxLength(5)
        self.input_cantidad.setAlignment(QtCore.Qt.AlignCenter)
        self.input_cantidad.setObjectName("input_cantidad")
        self.tcant = QtWidgets.QLabel(self.groupBox_datosContacto)
        self.tcant.setGeometry(QtCore.QRect(520, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tcant.setFont(font)
        self.tcant.setObjectName("tcant")
        self.boton_agregarItem = QtWidgets.QPushButton(self.groupBox_datosContacto)
        self.boton_agregarItem.setGeometry(QtCore.QRect(870, 30, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boton_agregarItem.setFont(font)
        self.boton_agregarItem.setObjectName("boton_agregarItem")
        self.boton_agregarprod = QtWidgets.QPushButton(self.groupBox_datosContacto)
        self.boton_agregarprod.setGeometry(QtCore.QRect(850, 190, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boton_agregarprod.setFont(font)
        self.boton_agregarprod.setObjectName("boton_agregarprod")
        self.boton_buscar = QtWidgets.QPushButton(self.groupBox_datosContacto)
        self.boton_buscar.setGeometry(QtCore.QRect(850, 150, 141, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boton_buscar.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Users/Maxi/.designer/..Imagenes/buscar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_buscar.setIcon(icon)
        self.boton_buscar.setIconSize(QtCore.QSize(15, 20))
        self.boton_buscar.setObjectName("boton_buscar")
        self.input_precio = QtWidgets.QLineEdit(self.groupBox_datosContacto)
        self.input_precio.setGeometry(QtCore.QRect(760, 30, 91, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_precio.setFont(font)
        self.input_precio.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_precio.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_precio.setText("")
        self.input_precio.setMaxLength(5)
        self.input_precio.setAlignment(QtCore.Qt.AlignCenter)
        self.input_precio.setObjectName("input_precio")
        self.precio = QtWidgets.QLabel(self.groupBox_datosContacto)
        self.precio.setGeometry(QtCore.QRect(700, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.precio.setFont(font)
        self.precio.setObjectName("precio")
        self.precio_2 = QtWidgets.QLabel(self.groupBox_datosContacto)
        self.precio_2.setGeometry(QtCore.QRect(490, 300, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.precio_2.setFont(font)
        self.precio_2.setObjectName("precio_2")
        self.input_iva = QtWidgets.QLineEdit(self.groupBox_datosContacto)
        self.input_iva.setEnabled(False)
        self.input_iva.setGeometry(QtCore.QRect(570, 300, 131, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_iva.setFont(font)
        self.input_iva.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_iva.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_iva.setText("")
        self.input_iva.setMaxLength(5)
        self.input_iva.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_iva.setObjectName("input_iva")
        self.input_subtotal = QtWidgets.QLineEdit(self.groupBox_datosContacto)
        self.input_subtotal.setEnabled(False)
        self.input_subtotal.setGeometry(QtCore.QRect(95, 300, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_subtotal.setFont(font)
        self.input_subtotal.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_subtotal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_subtotal.setText("")
        self.input_subtotal.setMaxLength(5)
        self.input_subtotal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_subtotal.setObjectName("input_subtotal")
        self.precio_3 = QtWidgets.QLabel(self.groupBox_datosContacto)
        self.precio_3.setGeometry(QtCore.QRect(20, 300, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.precio_3.setFont(font)
        self.precio_3.setObjectName("precio_3")
        self.precio_4 = QtWidgets.QLabel(self.groupBox_datosContacto)
        self.precio_4.setGeometry(QtCore.QRect(250, 300, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.precio_4.setFont(font)
        self.precio_4.setObjectName("precio_4")
        self.input_descuento_2 = QtWidgets.QLineEdit(self.groupBox_datosContacto)
        self.input_descuento_2.setEnabled(False)
        self.input_descuento_2.setGeometry(QtCore.QRect(340, 300, 131, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_descuento_2.setFont(font)
        self.input_descuento_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_descuento_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_descuento_2.setText("")
        self.input_descuento_2.setMaxLength(5)
        self.input_descuento_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_descuento_2.setObjectName("input_descuento_2")
        self.input_importe = QtWidgets.QLineEdit(self.groupBox_datosContacto)
        self.input_importe.setEnabled(False)
        self.input_importe.setGeometry(QtCore.QRect(850, 300, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_importe.setFont(font)
        self.input_importe.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_importe.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_importe.setText("")
        self.input_importe.setMaxLength(5)
        self.input_importe.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_importe.setObjectName("input_importe")
        self.precio_5 = QtWidgets.QLabel(self.groupBox_datosContacto)
        self.precio_5.setGeometry(QtCore.QRect(715, 300, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.precio_5.setFont(font)
        self.precio_5.setObjectName("precio_5")
        self.line = QtWidgets.QFrame(self.groupBox_datosContacto)
        self.line.setGeometry(QtCore.QRect(0, 260, 1001, 41))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.input_nombreProd = QtWidgets.QLineEdit(self.groupBox_datosContacto)
        self.input_nombreProd.setGeometry(QtCore.QRect(360, 30, 151, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_nombreProd.setFont(font)
        self.input_nombreProd.setText("")
        self.input_nombreProd.setMaxLength(14)
        self.input_nombreProd.setAlignment(QtCore.Qt.AlignCenter)
        self.input_nombreProd.setPlaceholderText("")
        self.input_nombreProd.setObjectName("input_nombreProd")
        self.codprod_2 = QtWidgets.QLabel(self.groupBox_datosContacto)
        self.codprod_2.setGeometry(QtCore.QRect(280, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.codprod_2.setFont(font)
        self.codprod_2.setObjectName("codprod_2")
        self.input_codprod = QtWidgets.QLineEdit(self.groupBox_datosContacto)
        self.input_codprod.setGeometry(QtCore.QRect(155, 30, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_codprod.setFont(font)
        self.input_codprod.setText("")
        self.input_codprod.setMaxLength(14)
        self.input_codprod.setAlignment(QtCore.Qt.AlignCenter)
        self.input_codprod.setPlaceholderText("")
        self.input_codprod.setObjectName("input_codprod")
        self.boton_remover = QtWidgets.QPushButton(self.groupBox_datosContacto)
        self.boton_remover.setGeometry(QtCore.QRect(670, 100, 141, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boton_remover.setFont(font)
        self.boton_remover.setIcon(icon)
        self.boton_remover.setIconSize(QtCore.QSize(15, 20))
        self.boton_remover.setObjectName("boton_remover")
        self.input_descuento = QtWidgets.QLineEdit(self.groupBox_datosContacto)
        self.input_descuento.setEnabled(True)
        self.input_descuento.setGeometry(QtCore.QRect(145, 230, 91, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_descuento.setFont(font)
        self.input_descuento.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_descuento.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_descuento.setMaxLength(5)
        self.input_descuento.setAlignment(QtCore.Qt.AlignCenter)
        self.input_descuento.setObjectName("input_descuento")
        self.precio_6 = QtWidgets.QLabel(self.groupBox_datosContacto)
        self.precio_6.setGeometry(QtCore.QRect(15, 230, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.precio_6.setFont(font)
        self.precio_6.setObjectName("precio_6")
        self.boton_agregarDescuento = QtWidgets.QPushButton(self.groupBox_datosContacto)
        self.boton_agregarDescuento.setGeometry(QtCore.QRect(250, 230, 141, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boton_agregarDescuento.setFont(font)
        self.boton_agregarDescuento.setObjectName("boton_agregarDescuento")
        self.groupBox_generales = QtWidgets.QGroupBox(FacturaDeCompra)
        self.groupBox_generales.setGeometry(QtCore.QRect(10, 60, 1001, 141))
        self.groupBox_generales.setMinimumSize(QtCore.QSize(421, 1))
        self.groupBox_generales.setMaximumSize(QtCore.QSize(1200, 900))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_generales.setFont(font)
        self.groupBox_generales.setAutoFillBackground(False)
        self.groupBox_generales.setFlat(False)
        self.groupBox_generales.setObjectName("groupBox_generales")
        self.label_codProv = QtWidgets.QLabel(self.groupBox_generales)
        self.label_codProv.setGeometry(QtCore.QRect(15, 30, 151, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_codProv.setFont(font)
        self.label_codProv.setObjectName("label_codProv")
        self.input_facCompra = QtWidgets.QLineEdit(self.groupBox_generales)
        self.input_facCompra.setEnabled(False)
        self.input_facCompra.setGeometry(QtCore.QRect(185, 30, 260, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_facCompra.setFont(font)
        self.input_facCompra.setMaxLength(40)
        self.input_facCompra.setAlignment(QtCore.Qt.AlignCenter)
        self.input_facCompra.setObjectName("input_facCompra")
        self.label_nameProv = QtWidgets.QLabel(self.groupBox_generales)
        self.label_nameProv.setGeometry(QtCore.QRect(475, 30, 83, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_nameProv.setFont(font)
        self.label_nameProv.setObjectName("label_nameProv")
        self.input_nroFac = QtWidgets.QLineEdit(self.groupBox_generales)
        self.input_nroFac.setGeometry(QtCore.QRect(185, 65, 260, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_nroFac.setFont(font)
        self.input_nroFac.setText("")
        self.input_nroFac.setMaxLength(12)
        self.input_nroFac.setAlignment(QtCore.Qt.AlignCenter)
        self.input_nroFac.setObjectName("input_nroFac")
        self.cuilOcuit = QtWidgets.QLabel(self.groupBox_generales)
        self.cuilOcuit.setGeometry(QtCore.QRect(15, 65, 116, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.cuilOcuit.setFont(font)
        self.cuilOcuit.setObjectName("cuilOcuit")
        self.label_ciudad = QtWidgets.QLabel(self.groupBox_generales)
        self.label_ciudad.setGeometry(QtCore.QRect(475, 100, 120, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_ciudad.setFont(font)
        self.label_ciudad.setObjectName("label_ciudad")
        self.input_tipoCompra = QtWidgets.QComboBox(self.groupBox_generales)
        self.input_tipoCompra.setEnabled(True)
        self.input_tipoCompra.setGeometry(QtCore.QRect(645, 100, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.input_tipoCompra.setFont(font)
        self.input_tipoCompra.setObjectName("input_tipoCompra")
        self.input_tipoCompra.addItem("")
        self.input_tipoCompra.addItem("")
        self.date_fechaEmision = QtWidgets.QDateEdit(self.groupBox_generales)
        self.date_fechaEmision.setGeometry(QtCore.QRect(185, 100, 81, 20))
        self.date_fechaEmision.setObjectName("date_fechaEmision")
        self.label_ciudad_2 = QtWidgets.QLabel(self.groupBox_generales)
        self.label_ciudad_2.setGeometry(QtCore.QRect(15, 100, 133, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_ciudad_2.setFont(font)
        self.label_ciudad_2.setObjectName("label_ciudad_2")
        self.botonbuscar_prov = QtWidgets.QPushButton(self.groupBox_generales)
        self.botonbuscar_prov.setGeometry(QtCore.QRect(862, 30, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botonbuscar_prov.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Imagenes/buscar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonbuscar_prov.setIcon(icon1)
        self.botonbuscar_prov.setIconSize(QtCore.QSize(15, 20))
        self.botonbuscar_prov.setObjectName("botonbuscar_prov")
        self.boton_agregarprov = QtWidgets.QPushButton(self.groupBox_generales)
        self.boton_agregarprov.setGeometry(QtCore.QRect(935, 30, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boton_agregarprov.setFont(font)
        self.boton_agregarprov.setObjectName("boton_agregarprov")
        self.cuilOcuit_2 = QtWidgets.QLabel(self.groupBox_generales)
        self.cuilOcuit_2.setGeometry(QtCore.QRect(475, 65, 151, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.cuilOcuit_2.setFont(font)
        self.cuilOcuit_2.setObjectName("cuilOcuit_2")
        self.input_nroCuil = QtWidgets.QLineEdit(self.groupBox_generales)
        self.input_nroCuil.setEnabled(False)
        self.input_nroCuil.setGeometry(QtCore.QRect(645, 65, 291, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_nroCuil.setFont(font)
        self.input_nroCuil.setText("")
        self.input_nroCuil.setMaxLength(12)
        self.input_nroCuil.setAlignment(QtCore.Qt.AlignCenter)
        self.input_nroCuil.setObjectName("input_nroCuil")
        self.input_provFact = QtWidgets.QLineEdit(self.groupBox_generales)
        self.input_provFact.setGeometry(QtCore.QRect(645, 30, 211, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_provFact.setFont(font)
        self.input_provFact.setText("")
        self.input_provFact.setMaxLength(40)
        self.input_provFact.setAlignment(QtCore.Qt.AlignCenter)
        self.input_provFact.setObjectName("input_provFact")
        self.boton_guardar = QtWidgets.QPushButton(FacturaDeCompra)
        self.boton_guardar.setGeometry(QtCore.QRect(794, 590, 91, 27))
        self.boton_guardar.setMaximumSize(QtCore.QSize(200, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.boton_guardar.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_guardar.setFont(font)
        self.boton_guardar.setObjectName("boton_guardar")
        self.boton_cancelar = QtWidgets.QPushButton(FacturaDeCompra)
        self.boton_cancelar.setGeometry(QtCore.QRect(900, 590, 91, 27))
        self.boton_cancelar.setMaximumSize(QtCore.QSize(200, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.boton_cancelar.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_cancelar.setFont(font)
        self.boton_cancelar.setObjectName("boton_cancelar")

        self.retranslateUi(FacturaDeCompra)
        QtCore.QMetaObject.connectSlotsByName(FacturaDeCompra)
        FacturaDeCompra.setTabOrder(self.input_facCompra, self.input_provFact)
        FacturaDeCompra.setTabOrder(self.input_provFact, self.botonbuscar_prov)
        FacturaDeCompra.setTabOrder(self.botonbuscar_prov, self.boton_agregarprov)
        FacturaDeCompra.setTabOrder(self.boton_agregarprov, self.input_nroFac)
        FacturaDeCompra.setTabOrder(self.input_nroFac, self.input_nroCuil)
        FacturaDeCompra.setTabOrder(self.input_nroCuil, self.date_fechaEmision)
        FacturaDeCompra.setTabOrder(self.date_fechaEmision, self.input_tipoCompra)
        FacturaDeCompra.setTabOrder(self.input_tipoCompra, self.input_nombreProd)
        FacturaDeCompra.setTabOrder(self.input_nombreProd, self.input_cantidad)
        FacturaDeCompra.setTabOrder(self.input_cantidad, self.input_precio)
        FacturaDeCompra.setTabOrder(self.input_precio, self.boton_agregarItem)
        FacturaDeCompra.setTabOrder(self.boton_agregarItem, self.boton_buscar)
        FacturaDeCompra.setTabOrder(self.boton_buscar, self.boton_agregarprod)
        FacturaDeCompra.setTabOrder(self.boton_agregarprod, self.input_subtotal)
        FacturaDeCompra.setTabOrder(self.input_subtotal, self.input_descuento_2)
        FacturaDeCompra.setTabOrder(self.input_descuento_2, self.input_iva)
        FacturaDeCompra.setTabOrder(self.input_iva, self.input_importe)
        FacturaDeCompra.setTabOrder(self.input_importe, self.boton_guardar)
        FacturaDeCompra.setTabOrder(self.boton_guardar, self.boton_cancelar)
        FacturaDeCompra.setTabOrder(self.boton_cancelar, self.table_venta)

    #Auto Complete de Nombre Proveedor
        self.completer_nameProv = QCompleter(self.proveedor.autoComplete())
        self.completer_nameProv.setCaseSensitivity(Qt.CaseInsensitive)
        self.input_provFact.setCompleter(self.completer_nameProv)
    #Auto Complete de cod de barras producto
        nombre = self.input_provFact.text()
        self.completer_codProd = QCompleter(self.product.autoCompleteCodProd(nombre))
        self.input_codprod.setCompleter(self.completer_codProd)
    #Auto Complete de Nombre producto
        self.completer_nameProd = QCompleter(self.product.autoCompleteNameProd(nombre))
        self.completer_nameProd.setCaseSensitivity(Qt.CaseInsensitive)
        self.input_nombreProd.setCompleter(self.completer_nameProd)

        self.timer()

        self.input_subtotal.setMaxLength(10)
        self.input_subtotal.setValidator(QDoubleValidator(0.99,99.99,2))

        self.input_iva.setMaxLength(10)
        self.input_iva.setValidator(QDoubleValidator(0.99,99.99,2))

        self.input_importe.setMaxLength(10)
        self.input_importe.setValidator(QDoubleValidator(0.99,99.99,2))

#------------------------------------------------------------------------------

        self.a = self.boton_agregarItem.clicked.connect(lambda:self.facturaCompraController.aceptar(self.input_codprod.text(), self.input_cantidad.text(),self.input_precio.text(),self.input_subtotal.text()))
        
        self.d = self.boton_guardar.clicked.connect(lambda: self.facturaCompraController.guardar(self.input_facCompra.text(), self.input_provFact.text(), self.input_nroFac.text(), self.input_nroCuil.text(), self.date_fechaEmision.text(), self.input_tipoCompra.currentText(), self.input_subtotal.text(), self.input_descuento_2.text(), self.input_iva.text(), self.input_importe.text())) 

        self.c = self.boton_cancelar.clicked.connect(lambda:self.facturaCompraController.cancelar(FacturaDeCompra))
 
        self.d = self.botonbuscar_prov.clicked.connect(lambda:self.facturaCompraController.buscarProv(self.input_provFact.text()))

        self.e = self.boton_agregarprov.clicked.connect(lambda:self.menuPrincipal.openProveedores(Ui_Proveedores,FacturaDeCompra))

        self.f = self.boton_agregarprod.clicked.connect(lambda:self.menuPrincipal.openCreateProduct(Ui_CreateProduct,FacturaDeCompra))

        self.g = self.boton_buscar.clicked.connect(lambda:self.menuPrincipal.openListaProductos(Ui_listaDeProductos,FacturaDeCompra))

        self.h = self.boton_remover.clicked.connect(lambda:self.facturaCompraController.remover(self.input_subtotal.text()))

        self.i = self.boton_agregarDescuento.clicked.connect(lambda: self.facturaCompraController.descuentoAgregado(self.input_descuento.text()))
#-------------------------------------------------------------------------------

    def retranslateUi(self, FacturaDeCompra):
        _translate = QtCore.QCoreApplication.translate
        FacturaDeCompra.setWindowTitle(_translate("FacturaDeCompra", "Carga Factura de Compra"))
        self.label.setText(_translate("FacturaDeCompra", "Factura de Compra"))
        self.groupBox_datosContacto.setTitle(_translate("FacturaDeCompra", "Item"))
        item = self.table_venta.verticalHeaderItem(0)
        item.setText(_translate("FacturaDeCompra", "1"))
        item = self.table_venta.verticalHeaderItem(1)
        item.setText(_translate("FacturaDeCompra", "2"))
        item = self.table_venta.verticalHeaderItem(2)
        item.setText(_translate("FacturaDeCompra", "3"))
        item = self.table_venta.verticalHeaderItem(3)
        item.setText(_translate("FacturaDeCompra", "4"))
        item = self.table_venta.verticalHeaderItem(4)
        item.setText(_translate("FacturaDeCompra", "5"))
        item = self.table_venta.verticalHeaderItem(5)
        item.setText(_translate("FacturaDeCompra", "6"))
        item = self.table_venta.verticalHeaderItem(6)
        item.setText(_translate("FacturaDeCompra", "7"))
        item = self.table_venta.verticalHeaderItem(7)
        item.setText(_translate("FacturaDeCompra", "8"))
        item = self.table_venta.verticalHeaderItem(8)
        item.setText(_translate("FacturaDeCompra", "9"))
        item = self.table_venta.verticalHeaderItem(9)
        item.setText(_translate("FacturaDeCompra", "10"))
        item = self.table_venta.verticalHeaderItem(10)
        item.setText(_translate("FacturaDeCompra", "11"))
        item = self.table_venta.verticalHeaderItem(11)
        item.setText(_translate("FacturaDeCompra", "12"))
        item = self.table_venta.verticalHeaderItem(12)
        item.setText(_translate("FacturaDeCompra", "13"))
        item = self.table_venta.verticalHeaderItem(13)
        item.setText(_translate("FacturaDeCompra", "14"))
        item = self.table_venta.verticalHeaderItem(14)
        item.setText(_translate("FacturaDeCompra", "15"))
        item = self.table_venta.verticalHeaderItem(15)
        item.setText(_translate("FacturaDeCompra", "16"))
        item = self.table_venta.verticalHeaderItem(16)
        item.setText(_translate("FacturaDeCompra", "17"))
        item = self.table_venta.verticalHeaderItem(17)
        item.setText(_translate("FacturaDeCompra", "18"))
        item = self.table_venta.verticalHeaderItem(18)
        item.setText(_translate("FacturaDeCompra", "19"))
        item = self.table_venta.verticalHeaderItem(19)
        item.setText(_translate("FacturaDeCompra", "20"))
        item = self.table_venta.verticalHeaderItem(20)
        item.setText(_translate("FacturaDeCompra", "21"))
        item = self.table_venta.verticalHeaderItem(21)
        item.setText(_translate("FacturaDeCompra", "22"))
        item = self.table_venta.verticalHeaderItem(22)
        item.setText(_translate("FacturaDeCompra", "23"))
        item = self.table_venta.verticalHeaderItem(23)
        item.setText(_translate("FacturaDeCompra", "24"))
        item = self.table_venta.verticalHeaderItem(24)
        item.setText(_translate("FacturaDeCompra", "25"))
        item = self.table_venta.verticalHeaderItem(25)
        item.setText(_translate("FacturaDeCompra", "26"))
        item = self.table_venta.verticalHeaderItem(26)
        item.setText(_translate("FacturaDeCompra", "27"))
        item = self.table_venta.verticalHeaderItem(27)
        item.setText(_translate("FacturaDeCompra", "28"))
        item = self.table_venta.verticalHeaderItem(28)
        item.setText(_translate("FacturaDeCompra", "29"))
        item = self.table_venta.verticalHeaderItem(29)
        item.setText(_translate("FacturaDeCompra", "30"))
        item = self.table_venta.verticalHeaderItem(30)
        item.setText(_translate("FacturaDeCompra", "31"))
        item = self.table_venta.verticalHeaderItem(31)
        item.setText(_translate("FacturaDeCompra", "32"))
        item = self.table_venta.verticalHeaderItem(32)
        item.setText(_translate("FacturaDeCompra", "33"))
        item = self.table_venta.verticalHeaderItem(33)
        item.setText(_translate("FacturaDeCompra", "34"))
        item = self.table_venta.verticalHeaderItem(34)
        item.setText(_translate("FacturaDeCompra", "35"))
        item = self.table_venta.verticalHeaderItem(35)
        item.setText(_translate("FacturaDeCompra", "36"))
        item = self.table_venta.verticalHeaderItem(36)
        item.setText(_translate("FacturaDeCompra", "37"))
        item = self.table_venta.verticalHeaderItem(37)
        item.setText(_translate("FacturaDeCompra", "38"))
        item = self.table_venta.verticalHeaderItem(38)
        item.setText(_translate("FacturaDeCompra", "39"))
        item = self.table_venta.verticalHeaderItem(39)
        item.setText(_translate("FacturaDeCompra", "40"))
        item = self.table_venta.verticalHeaderItem(40)
        item.setText(_translate("FacturaDeCompra", "41"))
        item = self.table_venta.verticalHeaderItem(41)
        item.setText(_translate("FacturaDeCompra", "42"))
        item = self.table_venta.verticalHeaderItem(42)
        item.setText(_translate("FacturaDeCompra", "43"))
        item = self.table_venta.verticalHeaderItem(43)
        item.setText(_translate("FacturaDeCompra", "44"))
        item = self.table_venta.verticalHeaderItem(44)
        item.setText(_translate("FacturaDeCompra", "45"))
        item = self.table_venta.verticalHeaderItem(45)
        item.setText(_translate("FacturaDeCompra", "46"))
        item = self.table_venta.verticalHeaderItem(46)
        item.setText(_translate("FacturaDeCompra", "47"))
        item = self.table_venta.verticalHeaderItem(47)
        item.setText(_translate("FacturaDeCompra", "48"))
        item = self.table_venta.verticalHeaderItem(48)
        item.setText(_translate("FacturaDeCompra", "49"))
        item = self.table_venta.verticalHeaderItem(49)
        item.setText(_translate("FacturaDeCompra", "50"))
        item = self.table_venta.horizontalHeaderItem(0)
        item.setText(_translate("FacturaDeCompra", "Código Prod."))
        item = self.table_venta.horizontalHeaderItem(1)
        item.setText(_translate("FacturaDeCompra", "Cód. de Barras"))
        item = self.table_venta.horizontalHeaderItem(2)
        item.setText(_translate("FacturaDeCompra", "Producto"))
        item = self.table_venta.horizontalHeaderItem(3)
        item.setText(_translate("FacturaDeCompra", "Cantidad"))
        item = self.table_venta.horizontalHeaderItem(4)
        item.setText(_translate("FacturaDeCompra", "Precio Unit."))
        item = self.table_venta.horizontalHeaderItem(5)
        item.setText(_translate("FacturaDeCompra", "Subtotal"))
        __sortingEnabled = self.table_venta.isSortingEnabled()
        self.table_venta.setSortingEnabled(False)
        self.table_venta.setSortingEnabled(__sortingEnabled)
        self.codprod.setText(_translate("FacturaDeCompra", "Código de Barras:"))
        self.tcant.setText(_translate("FacturaDeCompra", "Cantidad:"))
        self.boton_agregarItem.setText(_translate("FacturaDeCompra", "Agregar Item"))
        self.boton_agregarprod.setText(_translate("FacturaDeCompra", "Crear Producto"))
        self.boton_buscar.setText(_translate("FacturaDeCompra", "Ver Lista Productos"))
        self.precio.setText(_translate("FacturaDeCompra", "Precio:"))
        self.precio_2.setText(_translate("FacturaDeCompra", "IVA 21%:"))
        self.precio_3.setText(_translate("FacturaDeCompra", "Subtotal:"))
        self.precio_4.setText(_translate("FacturaDeCompra", "Descuento:"))
        self.precio_5.setText(_translate("FacturaDeCompra", "IMPORTE TOTAL:"))
        self.codprod_2.setText(_translate("FacturaDeCompra", "Producto:"))
        self.boton_remover.setText(_translate("FacturaDeCompra", "Remover Item"))
        self.input_descuento.setText(_translate("FacturaDeCompra", "0"))
        self.precio_6.setText(_translate("FacturaDeCompra", "Descuento (%):"))
        self.boton_agregarDescuento.setText(_translate("FacturaDeCompra", "Agregar Descuento"))
        self.groupBox_generales.setTitle(_translate("FacturaDeCompra", "Datos"))
        self.label_codProv.setText(_translate("FacturaDeCompra", "<html><head/><body><p>Tipo de Documento:</p></body></html>"))
        self.input_facCompra.setText(_translate("FacturaDeCompra", "Factura de Compra"))
        self.input_facCompra.setPlaceholderText(_translate("FacturaDeCompra", "Apellido y Nombre Proveedor"))
        self.label_nameProv.setText(_translate("FacturaDeCompra", "<html><head/><body><p>Proveedor:</p></body></html>"))
        self.input_nroFac.setPlaceholderText(_translate("FacturaDeCompra", "Nro de Factura"))
        self.cuilOcuit.setText(_translate("FacturaDeCompra", "<html><head/><body><p>Nro de Factura:</p></body></html>"))
        self.label_ciudad.setText(_translate("FacturaDeCompra", "<html><head/><body><p>Tipo de Compra:</p><p><br/></p></body></html>"))
        self.input_tipoCompra.setItemText(0, _translate("FacturaDeCompra", "Cuenta Corriente"))
        self.input_tipoCompra.setItemText(1, _translate("FacturaDeCompra", "Contado"))
        self.label_ciudad_2.setText(_translate("FacturaDeCompra", "<html><head/><body><p>Fecha de Emisión:</p><p><br/></p></body></html>"))
        self.botonbuscar_prov.setText(_translate("FacturaDeCompra", "Agregar"))
        self.boton_agregarprov.setText(_translate("FacturaDeCompra", "Crear"))
        self.cuilOcuit_2.setText(_translate("FacturaDeCompra", "<html><head/><body><p>Nro de CUIL o CUIT:</p></body></html>"))
        self.input_nroCuil.setPlaceholderText(_translate("FacturaDeCompra", "Nro de CUIL o CUIT"))
        self.input_provFact.setPlaceholderText(_translate("FacturaDeCompra", "Proveedor"))
        self.boton_guardar.setText(_translate("FacturaDeCompra", "Guardar"))
        self.boton_cancelar.setText(_translate("FacturaDeCompra", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FacturaDeCompra = QtWidgets.QWidget()
    ui = Ui_FacturaDeCompra()
    ui.setupUi(FacturaDeCompra)
    FacturaDeCompra.show()
    sys.exit(app.exec_())
