
import sys
import os

myDir = os.getcwd()
sys.path.append(myDir)

from Controllers.modificarProductoController import modificarProductoController
from PyQt5 import QtCore, QtGui, QtWidgets
from Models.Product import Product
from Database.Connection import connection


class Ui_editEraseProduct(object):
    def __init__(self):
        self.product = Product(connection())
        self.modificarProducto = modificarProductoController(self)
        

    def setupUi(self, editEraseProduct):
        editEraseProduct.setObjectName("editEraseProduct")
        editEraseProduct.resize(899, 700)
        self.btn_saveChanges = QtWidgets.QPushButton(editEraseProduct)
        self.btn_saveChanges.setGeometry(QtCore.QRect(130, 610, 300, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_saveChanges.setFont(font)
        self.btn_saveChanges.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_saveChanges.setObjectName("btn_saveChanges")
        self.label_editEraseProd = QtWidgets.QLabel(editEraseProduct)
        self.label_editEraseProd.setGeometry(QtCore.QRect(30, 10, 361, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_editEraseProd.setFont(font)
        self.label_editEraseProd.setObjectName("label_editEraseProd")
        self.btn_exit = QtWidgets.QPushButton(editEraseProduct)
        self.btn_exit.setGeometry(QtCore.QRect(300, 660, 300, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setObjectName("btn_exit")
        self.btn_eraseProd = QtWidgets.QPushButton(editEraseProduct)
        self.btn_eraseProd.setGeometry(QtCore.QRect(460, 610, 300, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_eraseProd.setFont(font)
        self.btn_eraseProd.setObjectName("btn_eraseProd")
        self.label_datBasic = QtWidgets.QLabel(editEraseProduct)
        self.label_datBasic.setGeometry(QtCore.QRect(20, 60, 131, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_datBasic.setFont(font)
        self.label_datBasic.setObjectName("label_datBasic")
        self.layoutWidget = QtWidgets.QWidget(editEraseProduct)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 90, 281, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_cod = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_cod.setFont(font)
        self.label_cod.setObjectName("label_cod")
        self.verticalLayout.addWidget(self.label_cod)
        self.input_cod = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_cod.setFont(font)
        self.input_cod.setText("")
        self.input_cod.setAlignment(QtCore.Qt.AlignCenter)
        self.input_cod.setObjectName("input_cod")
        self.verticalLayout.addWidget(self.input_cod)
        self.layoutWidget1 = QtWidgets.QWidget(editEraseProduct)
        self.layoutWidget1.setGeometry(QtCore.QRect(400, 90, 441, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_cant = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_cant.setFont(font)
        self.label_cant.setObjectName("label_cant")
        self.verticalLayout_2.addWidget(self.label_cant)
        self.input_prod = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_prod.setFont(font)
        self.input_prod.setText("")
        self.input_prod.setAlignment(QtCore.Qt.AlignCenter)
        self.input_prod.setObjectName("input_prod")
        self.verticalLayout_2.addWidget(self.input_prod)
        self.layoutWidget2 = QtWidgets.QWidget(editEraseProduct)
        self.layoutWidget2.setGeometry(QtCore.QRect(50, 170, 141, 61))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_descrip = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_descrip.setFont(font)
        self.label_descrip.setObjectName("label_descrip")
        self.verticalLayout_3.addWidget(self.label_descrip)
        self.box_cat = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.box_cat.setFont(font)
        self.box_cat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.box_cat.setObjectName("box_cat")
        self.box_cat.addItem("")
        self.verticalLayout_3.addWidget(self.box_cat)
        self.layoutWidget3 = QtWidgets.QWidget(editEraseProduct)
        self.layoutWidget3.setGeometry(QtCore.QRect(220, 170, 141, 61))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_categoria = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_categoria.setFont(font)
        self.label_categoria.setObjectName("label_categoria")
        self.verticalLayout_4.addWidget(self.label_categoria)
        self.box_subCat = QtWidgets.QComboBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.box_subCat.setFont(font)
        self.box_subCat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.box_subCat.setObjectName("box_subCat")
        self.box_subCat.addItem("")
        self.verticalLayout_4.addWidget(self.box_subCat)
        self.layoutWidget4 = QtWidgets.QWidget(editEraseProduct)
        self.layoutWidget4.setGeometry(QtCore.QRect(400, 170, 281, 61))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_precio = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_precio.setFont(font)
        self.label_precio.setObjectName("label_precio")
        self.verticalLayout_5.addWidget(self.label_precio)
        self.box_marca = QtWidgets.QComboBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.box_marca.setFont(font)
        self.box_marca.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.box_marca.setObjectName("box_marca")
        self.box_marca.addItem("")
        self.verticalLayout_5.addWidget(self.box_marca)
        self.frame = QtWidgets.QFrame(editEraseProduct)
        self.frame.setGeometry(QtCore.QRect(10, 480, 881, 111))
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.label_datCompraVenta = QtWidgets.QLabel(self.frame)
        self.label_datCompraVenta.setGeometry(QtCore.QRect(10, 10, 211, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_datCompraVenta.setFont(font)
        self.label_datCompraVenta.setObjectName("label_datCompraVenta")
        self.layoutWidget5 = QtWidgets.QWidget(self.frame)
        self.layoutWidget5.setGeometry(QtCore.QRect(430, 40, 301, 51))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_precVenta = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_precVenta.setFont(font)
        self.label_precVenta.setObjectName("label_precVenta")
        self.verticalLayout_12.addWidget(self.label_precVenta)
        self.input_precVenta = QtWidgets.QLineEdit(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_precVenta.setFont(font)
        self.input_precVenta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.input_precVenta.setObjectName("input_precVenta")
        self.verticalLayout_12.addWidget(self.input_precVenta)
        self.layoutWidget6 = QtWidgets.QWidget(self.frame)
        self.layoutWidget6.setGeometry(QtCore.QRect(40, 40, 301, 51))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_costCompr = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_costCompr.setFont(font)
        self.label_costCompr.setObjectName("label_costCompr")
        self.verticalLayout_11.addWidget(self.label_costCompr)
        self.input_costCompra = QtWidgets.QLineEdit(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_costCompra.setFont(font)
        self.input_costCompra.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.input_costCompra.setObjectName("input_costCompra")
        self.verticalLayout_11.addWidget(self.input_costCompra)
        self.frame_2 = QtWidgets.QFrame(editEraseProduct)
        self.frame_2.setGeometry(QtCore.QRect(10, 260, 881, 201))
        self.frame_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.label_datStock = QtWidgets.QLabel(self.frame_2)
        self.label_datStock.setGeometry(QtCore.QRect(10, 10, 131, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_datStock.setFont(font)
        self.label_datStock.setObjectName("label_datStock")
        self.layoutWidget7 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget7.setGeometry(QtCore.QRect(210, 40, 181, 61))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_uniMed = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_uniMed.setFont(font)
        self.label_uniMed.setObjectName("label_uniMed")
        self.verticalLayout_7.addWidget(self.label_uniMed)
        self.box_uniMedi = QtWidgets.QComboBox(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.box_uniMedi.setFont(font)
        self.box_uniMedi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.box_uniMedi.setObjectName("box_uniMedi")
        self.box_uniMedi.addItem("")
        self.verticalLayout_7.addWidget(self.box_uniMedi)
        self.layoutWidget8 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget8.setGeometry(QtCore.QRect(430, 40, 361, 61))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_codBarra = QtWidgets.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_codBarra.setFont(font)
        self.label_codBarra.setObjectName("label_codBarra")
        self.verticalLayout_8.addWidget(self.label_codBarra)
        self.input_codBarra = QtWidgets.QLineEdit(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_codBarra.setFont(font)
        self.input_codBarra.setAlignment(QtCore.Qt.AlignCenter)
        self.input_codBarra.setObjectName("input_codBarra")
        self.verticalLayout_8.addWidget(self.input_codBarra)
        self.layoutWidget9 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget9.setGeometry(QtCore.QRect(40, 40, 141, 61))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_tipoUni = QtWidgets.QLabel(self.layoutWidget9)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_tipoUni.setFont(font)
        self.label_tipoUni.setObjectName("label_tipoUni")
        self.verticalLayout_6.addWidget(self.label_tipoUni)
        self.box_tipoUnid = QtWidgets.QComboBox(self.layoutWidget9)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.box_tipoUnid.setFont(font)
        self.box_tipoUnid.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.box_tipoUnid.setObjectName("box_tipoUnid")
        self.box_tipoUnid.addItem("")
        self.verticalLayout_6.addWidget(self.box_tipoUnid)
        self.layoutWidget10 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget10.setGeometry(QtCore.QRect(430, 130, 301, 51))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_puntPedi = QtWidgets.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_puntPedi.setFont(font)
        self.label_puntPedi.setObjectName("label_puntPedi")
        self.verticalLayout_10.addWidget(self.label_puntPedi)
        self.input_puntoPedido = QtWidgets.QLineEdit(self.layoutWidget10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_puntoPedido.setFont(font)
        self.input_puntoPedido.setAlignment(QtCore.Qt.AlignCenter)
        self.input_puntoPedido.setObjectName("input_puntoPedido")
        self.verticalLayout_10.addWidget(self.input_puntoPedido)
        self.layoutWidget11 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget11.setGeometry(QtCore.QRect(40, 130, 301, 51))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget11)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_cantMinStock = QtWidgets.QLabel(self.layoutWidget11)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_cantMinStock.setFont(font)
        self.label_cantMinStock.setObjectName("label_cantMinStock")
        self.verticalLayout_9.addWidget(self.label_cantMinStock)
        self.input_cantMinStock = QtWidgets.QLineEdit(self.layoutWidget11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_cantMinStock.setFont(font)
        self.input_cantMinStock.setAlignment(QtCore.Qt.AlignCenter)
        self.input_cantMinStock.setObjectName("input_cantMinStock")
        self.verticalLayout_9.addWidget(self.input_cantMinStock)
        self.frame_3 = QtWidgets.QFrame(editEraseProduct)
        self.frame_3.setGeometry(QtCore.QRect(10, 50, 881, 191))
        self.frame_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.Botonbuscar = QtWidgets.QPushButton(self.frame_3)
        self.Botonbuscar.setGeometry(QtCore.QRect(330, 60, 31, 30))
        self.Botonbuscar.setMinimumSize(QtCore.QSize(10, 10))
        self.Botonbuscar.setMaximumSize(QtCore.QSize(90, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.Botonbuscar.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Prog3/Sistema_Tweety/Imagenes/buscar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Botonbuscar.setIcon(icon)
        self.Botonbuscar.setIconSize(QtCore.QSize(15, 20))
        self.Botonbuscar.setObjectName("Botonbuscar")
        self.Botonbuscar_2 = QtWidgets.QPushButton(self.frame_3)
        self.Botonbuscar_2.setGeometry(QtCore.QRect(840, 60, 31, 30))
        self.Botonbuscar_2.setMinimumSize(QtCore.QSize(10, 10))
        self.Botonbuscar_2.setMaximumSize(QtCore.QSize(90, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.Botonbuscar_2.setPalette(palette)
        self.Botonbuscar_2.setIcon(icon)
        self.Botonbuscar_2.setIconSize(QtCore.QSize(15, 20))
        self.Botonbuscar_2.setObjectName("Botonbuscar_2")
        self.widget = QtWidgets.QWidget(editEraseProduct)
        self.widget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.widget.setObjectName("widget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget1 = QtWidgets.QWidget(editEraseProduct)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.frame.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.btn_saveChanges.raise_()
        self.label_editEraseProd.raise_()
        self.btn_exit.raise_()
        self.btn_eraseProd.raise_()
        self.label_datBasic.raise_()

        self.retranslateUi(editEraseProduct)
        QtCore.QMetaObject.connectSlotsByName(editEraseProduct)

        
        
        #--------------------Events--------------------------------------
        self.l = self.btn_saveChanges.clicked.connect(lambda:self.modificarProducto.modificarProducto(editEraseProduct))
        self.c = self.btn_eraseProd.clicked.connect(lambda:self.modificarProducto.borrar())
        self.e = self.btn_exit.clicked.connect(lambda:self.modificarProducto.salir(editEraseProduct))
        #--------------------End Events---------------------------------
        # self.input_prod.setText(str(product[1]))
        # self.input_cantMinStock.setText(product[8])
        # self.input_puntoPedido.setText(product[9])
        # self.input_costCompra.setText(product[10])
        # self.input_precVenta.setText(product[11])

    def retranslateUi(self, editEraseProduct):
        _translate = QtCore.QCoreApplication.translate
        editEraseProduct.setWindowTitle(_translate("editEraseProduct", "Editar o Eliminar Producto"))
        self.btn_saveChanges.setText(_translate("editEraseProduct", "Guardar Cambios"))
        self.label_editEraseProd.setText(_translate("editEraseProduct", "Editar o Eliminar Producto"))
        self.btn_exit.setText(_translate("editEraseProduct", "Salir"))
        self.btn_eraseProd.setText(_translate("editEraseProduct", "Eliminar Producto"))
        self.label_datBasic.setText(_translate("editEraseProduct", "- Datos Basicos"))
        self.label_cod.setText(_translate("editEraseProduct", "<html><head/><body><p>Código:</p></body></html>"))
        self.input_cod.setPlaceholderText(_translate("editEraseProduct", "Código"))
        self.label_cant.setText(_translate("editEraseProduct", "<html><head/><body><p>Producto:</p></body></html>"))
        self.input_prod.setPlaceholderText(_translate("editEraseProduct", "Producto"))
        self.label_descrip.setText(_translate("editEraseProduct", "Categoria:"))
        self.box_cat.setItemText(0, _translate("editEraseProduct", "Utiles"))
        self.label_categoria.setText(_translate("editEraseProduct", "Sub Categoría:"))
        self.box_subCat.setItemText(0, _translate("editEraseProduct", "Lapiceras"))
        self.label_precio.setText(_translate("editEraseProduct", "Marca:"))
        self.box_marca.setItemText(0, _translate("editEraseProduct", "Bic"))
        self.label_datCompraVenta.setText(_translate("editEraseProduct", "- Datos Compra/Venta"))
        self.label_precVenta.setText(_translate("editEraseProduct", "<html><head/><body><p>Precio de Venta:</p></body></html>"))
        self.input_precVenta.setPlaceholderText(_translate("editEraseProduct", "$0.00"))
        self.label_costCompr.setText(_translate("editEraseProduct", "<html><head/><body><p>Costo de Compra:</p></body></html>"))
        self.input_costCompra.setPlaceholderText(_translate("editEraseProduct", "$0.00"))
        self.label_datStock.setText(_translate("editEraseProduct", "- Datos Stock"))
        self.label_uniMed.setText(_translate("editEraseProduct", "<html><head/><body><p>Unidad de Medida:</p></body></html>"))
        self.box_uniMedi.setItemText(0, _translate("editEraseProduct", "Unidad"))
        self.label_codBarra.setText(_translate("editEraseProduct", "Código Barra:"))
        self.input_codBarra.setPlaceholderText(_translate("editEraseProduct", "Cód. Barra"))
        self.label_tipoUni.setText(_translate("editEraseProduct", "<html><head/><body><p>Tipo Unidad:</p></body></html>"))
        self.box_tipoUnid.setItemText(0, _translate("editEraseProduct", "Unidad"))
        self.label_puntPedi.setText(_translate("editEraseProduct", "<html><head/><body><p>Punto de Pedido:</p></body></html>"))
        self.input_puntoPedido.setPlaceholderText(_translate("editEraseProduct", "Punto de Pedido"))
        self.label_cantMinStock.setText(_translate("editEraseProduct", "<html><head/><body><p>Cantidad Minima Stock:</p></body></html>"))
        self.input_cantMinStock.setPlaceholderText(_translate("editEraseProduct", "Cant. Min. Stock"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editEraseProduct = QtWidgets.QWidget()
    ui = Ui_editEraseProduct()
    ui.setupUi(editEraseProduct)
    editEraseProduct.show()
    sys.exit(app.exec_())
