# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'motivoanulacionventa.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Motivo(object):
    def setupUi(self, Motivo):
        Motivo.setObjectName("Motivo")
        Motivo.resize(400, 268)
        Motivo.setStyleSheet("background-color: rgb(246, 255, 157);")
        self.label = QtWidgets.QLabel(Motivo)
        self.label.setGeometry(QtCore.QRect(50, 20, 221, 16))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.btn_aceptar = QtWidgets.QPushButton(Motivo)
        self.btn_aceptar.setGeometry(QtCore.QRect(90, 220, 75, 23))
        self.btn_aceptar.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.btn_aceptar.setObjectName("btn_aceptar")
        self.btn_cancelar = QtWidgets.QPushButton(Motivo)
        self.btn_cancelar.setGeometry(QtCore.QRect(240, 220, 75, 23))
        self.btn_cancelar.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.textEdit = QtWidgets.QTextEdit(Motivo)
        self.textEdit.setGeometry(QtCore.QRect(50, 60, 300, 150))
        self.textEdit.setMaximumSize(QtCore.QSize(300, 150))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setTabStopWidth(80)
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Motivo)
        QtCore.QMetaObject.connectSlotsByName(Motivo)

    def retranslateUi(self, Motivo):
        _translate = QtCore.QCoreApplication.translate
        Motivo.setWindowTitle(_translate("Motivo", "Motivo"))
        self.label.setText(_translate("Motivo", "Motivo de anulación de venta:"))
        self.btn_aceptar.setText(_translate("Motivo", "Aceptar"))
        self.btn_cancelar.setText(_translate("Motivo", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Motivo = QtWidgets.QWidget()
    ui = Ui_Motivo()
    ui.setupUi(Motivo)
    Motivo.show()
    sys.exit(app.exec_())
