# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proveedores.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_proveedores(object):
    def setupUi(self, proveedores):
        proveedores.setObjectName("proveedores")
        proveedores.resize(626, 431)
        self.label = QtWidgets.QLabel(proveedores)
        self.label.setGeometry(QtCore.QRect(180, 60, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(proveedores)
        QtCore.QMetaObject.connectSlotsByName(proveedores)

    def retranslateUi(self, proveedores):
        _translate = QtCore.QCoreApplication.translate
        proveedores.setWindowTitle(_translate("proveedores", "Form"))
        self.label.setText(_translate("proveedores", "PROVEEDORES"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    proveedores = QtWidgets.QWidget()
    ui = Ui_proveedores()
    ui.setupUi(proveedores)
    proveedores.show()
    sys.exit(app.exec_())
