import sys
import os

myDir = os.getcwd()
sys.path.append(myDir)

from PyQt5 import QtCore, QtGui, QtWidgets
from Controllers.registrarUsuarioController import RegistrarController
from Database.Connection import connection
from Models.User import User


class Ui_registrarUsuario(object):
    def __init__(self):
        self.registrar_controller = RegistrarController(self)
        self.user = User(connection())

    def setupUi(self, registrarUsuario):
        registrarUsuario.setObjectName("registrarUsuario")
        registrarUsuario.setEnabled(True)
        registrarUsuario.resize(786, 512)
        registrarUsuario.setStyleSheet("background-color: rgb(153,204,255);\n"
"QFrame{background-color:rgb(153,204,255)}\n"
"QLineEdit{background-color:rgb(255,255,255)}")
        self.label_confirm = QtWidgets.QLabel(registrarUsuario)
        self.label_confirm.setGeometry(QtCore.QRect(420, 330, 311, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_confirm.setFont(font)
        self.label_confirm.setAlignment(QtCore.Qt.AlignCenter)
        self.label_confirm.setObjectName("label_confirm")
        self.layoutWidget = QtWidgets.QWidget(registrarUsuario)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 20, 691, 47))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.layoutWidget1 = QtWidgets.QWidget(registrarUsuario)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 430, 766, 43))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_registrar = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_registrar.setMinimumSize(QtCore.QSize(310, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 135, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 135, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 135, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 135, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 135, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 135, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btn_registrar.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_registrar.setFont(font)
        self.btn_registrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_registrar.setStyleSheet("background-color:     rgb(51,102,255)\n"
"")
        self.btn_registrar.setObjectName("btn_registrar")
        self.horizontalLayout_2.addWidget(self.btn_registrar)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.btn_cancelar = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_cancelar.setMinimumSize(QtCore.QSize(310, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 135, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 135, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 135, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 135, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 135, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 135, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btn_cancelar.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancelar.setFont(font)
        self.btn_cancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancelar.setStyleSheet("background-color:     rgb(192,192,192)")
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.horizontalLayout_2.addWidget(self.btn_cancelar)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label = QtWidgets.QLabel(registrarUsuario)
        self.label.setGeometry(QtCore.QRect(130, 140, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(registrarUsuario)
        self.label_3.setGeometry(QtCore.QRect(130, 200, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(registrarUsuario)
        self.label_4.setGeometry(QtCore.QRect(130, 240, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.input_usuario = QtWidgets.QLineEdit(registrarUsuario)
        self.input_usuario.setGeometry(QtCore.QRect(360, 150, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_usuario.setFont(font)
        self.input_usuario.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_usuario.setMaxLength(20)
        self.input_usuario.setAlignment(QtCore.Qt.AlignCenter)
        self.input_usuario.setObjectName("input_usuario")
        self.input_password = QtWidgets.QLineEdit(registrarUsuario)
        self.input_password.setGeometry(QtCore.QRect(360, 200, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_password.setFont(font)
        self.input_password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_password.setMaxLength(20)
        self.input_password.setAlignment(QtCore.Qt.AlignCenter)
        self.input_password.setObjectName("input_password")
        self.repit_password = QtWidgets.QLineEdit(registrarUsuario)
        self.repit_password.setGeometry(QtCore.QRect(360, 250, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.repit_password.setFont(font)
        self.repit_password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.repit_password.setMaxLength(20)
        self.repit_password.setAlignment(QtCore.Qt.AlignCenter)
        self.repit_password.setObjectName("repit_password")
        self.label_5 = QtWidgets.QLabel(registrarUsuario)
        self.label_5.setGeometry(QtCore.QRect(130, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox_Rol = QtWidgets.QComboBox(registrarUsuario)
        self.comboBox_Rol.setGeometry(QtCore.QRect(360, 100, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_Rol.setFont(font)
        self.comboBox_Rol.setAcceptDrops(False)
        self.comboBox_Rol.setStyleSheet("\n"
"background-color: rgb(212, 212, 212);")
        self.comboBox_Rol.setObjectName("comboBox_Rol")
        self.comboBox_Rol.addItem("")
        self.comboBox_Rol.addItem("")
        self.comboBox_Rol.addItem("")

        self.retranslateUi(registrarUsuario)
        QtCore.QMetaObject.connectSlotsByName(registrarUsuario)

        self.a = self.btn_registrar.clicked.connect(lambda:self.registrar_controller.registrarUsuario(self.input_usuario.text(),self.input_password.text(),self.repit_password.text() ,self.comboBox_Rol.currentText()))

    def retranslateUi(self, registrarUsuario):
        _translate = QtCore.QCoreApplication.translate
        registrarUsuario.setWindowTitle(_translate("registrarUsuario", "Registro de usuarios"))
        self.label_confirm.setText(_translate("registrarUsuario", "<html><head/><body><p><span style=\" color:#ff0000;\">Las contraseñas no coinciden</span></p></body></html>"))
        self.label_2.setText(_translate("registrarUsuario", "Registro de usuarios"))
        self.btn_registrar.setText(_translate("registrarUsuario", "Registarse"))
        self.btn_cancelar.setText(_translate("registrarUsuario", "Cancelar"))
        self.label.setText(_translate("registrarUsuario", "Nuevo Usuario:"))
        self.label_3.setText(_translate("registrarUsuario", "Contraseña:"))
        self.label_4.setText(_translate("registrarUsuario", "Repita su contraseña:"))
        self.input_usuario.setPlaceholderText(_translate("registrarUsuario", "Nombre de usuario"))
        self.input_password.setPlaceholderText(_translate("registrarUsuario", "Contraseña"))
        self.repit_password.setPlaceholderText(_translate("registrarUsuario", "Repita su contraseña"))
        self.label_5.setText(_translate("registrarUsuario", "Rol:"))
        self.comboBox_Rol.setItemText(0, _translate("registrarUsuario", "Encargado de ventas"))
        self.comboBox_Rol.setItemText(1, _translate("registrarUsuario", "Encargado de compras"))
        self.comboBox_Rol.setItemText(2, _translate("registrarUsuario", "Encargado de deposito"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    registrarUsuario = QtWidgets.QWidget()
    ui = Ui_registrarUsuario()
    ui.setupUi(registrarUsuario)
    registrarUsuario.show()
    sys.exit(app.exec_())
