import sys
import os
from tkinter.tix import Form
from wsgiref.validate import validator
from pymysql import STRING
myDir = os.getcwd()
sys.path.append(myDir)


from PyQt5 import QtCore, QtGui, QtWidgets
from Controllers.ventaController import ventaController

from Models.Product import Product
from Models.cliente import Cliente

from Database.Connection import connection




class Ui_TicketFactura(object):
    def __init__(self):
        self.ventaController = ventaController(self)
        self.product = Product(connection())
        self.cliente= Cliente(connection())
        

    def setupUi(self, TicketFactura):
        TicketFactura.setObjectName("TicketFactura")
        TicketFactura.setEnabled(True)
        TicketFactura.resize(818, 715)
        font = QtGui.QFont()
        font.setPointSize(17)
        TicketFactura.setFont(font)
        self.label = QtWidgets.QLabel(TicketFactura)
        self.label.setGeometry(QtCore.QRect(320, 50, 51, 71))
        font = QtGui.QFont()
        font.setPointSize(45)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(TicketFactura)
        self.label_2.setGeometry(QtCore.QRect(380, 40, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(TicketFactura)
        self.label_3.setGeometry(QtCore.QRect(380, 90, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(TicketFactura)
        self.label_4.setGeometry(QtCore.QRect(500, 90, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(TicketFactura)
        self.line.setGeometry(QtCore.QRect(340, 10, 3, 50))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(TicketFactura)
        self.line_2.setGeometry(QtCore.QRect(330, 120, 20, 121))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_5 = QtWidgets.QLabel(TicketFactura)
        self.label_5.setGeometry(QtCore.QRect(380, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.input_nroTicket = QtWidgets.QLineEdit(TicketFactura)
        self.input_nroTicket.setEnabled(False)
        self.input_nroTicket.setGeometry(QtCore.QRect(590, 80, 113, 41))
        self.input_nroTicket.setMaxLength(5)
        self.input_nroTicket.setObjectName("input_nroTicket")
        self.input_fecha = QtWidgets.QLineEdit(TicketFactura)
        self.input_fecha.setEnabled(False)
        self.input_fecha.setGeometry(QtCore.QRect(460, 139, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.input_fecha.setFont(font)
        self.input_fecha.setMaxLength(10)
        self.input_fecha.setObjectName("input_fecha")
        self.label_7 = QtWidgets.QLabel(TicketFactura)
        self.label_7.setGeometry(QtCore.QRect(80, 100, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(TicketFactura)
        self.label_6.setGeometry(QtCore.QRect(60, 20, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Freestyle Script")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(TicketFactura)
        self.label_8.setGeometry(QtCore.QRect(70, 60, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(41)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(TicketFactura)
        self.label_9.setGeometry(QtCore.QRect(70, 120, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(TicketFactura)
        self.label_10.setGeometry(QtCore.QRect(120, 140, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(TicketFactura)
        self.label_11.setGeometry(QtCore.QRect(50, 170, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(TicketFactura)
        self.label_12.setGeometry(QtCore.QRect(100, 190, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.line_3 = QtWidgets.QFrame(TicketFactura)
        self.line_3.setGeometry(QtCore.QRect(50, 210, 291, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(TicketFactura)
        self.line_4.setGeometry(QtCore.QRect(50, 230, 291, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_13 = QtWidgets.QLabel(TicketFactura)
        self.label_13.setGeometry(QtCore.QRect(90, 220, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.line_5 = QtWidgets.QFrame(TicketFactura)
        self.line_5.setGeometry(QtCore.QRect(340, 230, 431, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(TicketFactura)
        self.line_6.setGeometry(QtCore.QRect(50, 230, 721, 41))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_14 = QtWidgets.QLabel(TicketFactura)
        self.label_14.setGeometry(QtCore.QRect(90, 320, 51, 21))
        self.label_14.setObjectName("label_14")
        self.input_iva = QtWidgets.QLineEdit(TicketFactura)
        self.input_iva.setGeometry(QtCore.QRect(140, 320, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_iva.setFont(font)
        self.input_iva.setMaxLength(30)
        self.input_iva.setObjectName("input_iva")
        self.label_15 = QtWidgets.QLabel(TicketFactura)
        self.label_15.setGeometry(QtCore.QRect(60, 250, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(TicketFactura)
        self.label_16.setGeometry(QtCore.QRect(60, 280, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.input_cliente = QtWidgets.QLineEdit(TicketFactura)
        self.input_cliente.setGeometry(QtCore.QRect(140, 260, 621, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.input_cliente.setFont(font)
        self.input_cliente.setMaxLength(40)
        self.input_cliente.setObjectName("input_cliente")
        self.input_domicilio = QtWidgets.QLineEdit(TicketFactura)
        self.input_domicilio.setGeometry(QtCore.QRect(140, 290, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.input_domicilio.setFont(font)
        self.input_domicilio.setMaxLength(30)
        self.input_domicilio.setObjectName("input_domicilio")
        self.label_17 = QtWidgets.QLabel(TicketFactura)
        self.label_17.setGeometry(QtCore.QRect(540, 320, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.input_cuit = QtWidgets.QLineEdit(TicketFactura)
        self.input_cuit.setGeometry(QtCore.QRect(590, 320, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_cuit.setFont(font)
        self.input_cuit.setMaxLength(13)
        self.input_cuit.setObjectName("input_cuit")
        self.label_18 = QtWidgets.QLabel(TicketFactura)
        self.label_18.setGeometry(QtCore.QRect(520, 350, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.input_ingBrutos = QtWidgets.QLineEdit(TicketFactura)
        self.input_ingBrutos.setGeometry(QtCore.QRect(590, 350, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_ingBrutos.setFont(font)
        self.input_ingBrutos.setMaxLength(20)
        self.input_ingBrutos.setObjectName("input_ingBrutos")
        self.label_19 = QtWidgets.QLabel(TicketFactura)
        self.label_19.setGeometry(QtCore.QRect(520, 380, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.input_nroRemito = QtWidgets.QLineEdit(TicketFactura)
        self.input_nroRemito.setGeometry(QtCore.QRect(590, 380, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_nroRemito.setFont(font)
        self.input_nroRemito.setMaxLength(30)
        self.input_nroRemito.setObjectName("input_nroRemito")
        self.label_20 = QtWidgets.QLabel(TicketFactura)
        self.label_20.setGeometry(QtCore.QRect(50, 350, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(TicketFactura)
        self.label_21.setGeometry(QtCore.QRect(60, 370, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.input_condVenta = QtWidgets.QLineEdit(TicketFactura)
        self.input_condVenta.setGeometry(QtCore.QRect(140, 360, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_condVenta.setFont(font)
        self.input_condVenta.setMaxLength(30)
        self.input_condVenta.setObjectName("input_condVenta")
        self.line_7 = QtWidgets.QFrame(TicketFactura)
        self.line_7.setGeometry(QtCore.QRect(50, 390, 721, 41))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(TicketFactura)
        self.line_8.setGeometry(QtCore.QRect(410, 310, 20, 101))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(TicketFactura)
        self.line_9.setGeometry(QtCore.QRect(40, 250, 20, 160))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(TicketFactura)
        self.line_10.setGeometry(QtCore.QRect(760, 250, 20, 160))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(TicketFactura)
        self.line_11.setGeometry(QtCore.QRect(760, 10, 20, 230))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(TicketFactura)
        self.line_12.setGeometry(QtCore.QRect(40, 10, 20, 230))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(TicketFactura)
        self.line_13.setGeometry(QtCore.QRect(50, -10, 721, 41))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.tableWidget = QtWidgets.QTableWidget(TicketFactura)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(50, 420, 721, 221))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(173)
        self.tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(10)
        self.label_22 = QtWidgets.QLabel(TicketFactura)
        self.label_22.setGeometry(QtCore.QRect(430, 280, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.input_nro = QtWidgets.QLineEdit(TicketFactura)
        self.input_nro.setGeometry(QtCore.QRect(470, 290, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.input_nro.setFont(font)
        self.input_nro.setMaxLength(5)
        self.input_nro.setObjectName("input_nro")
        self.label_4.setBuddy(self.input_nroTicket)
        self.label_5.setBuddy(self.input_fecha)
        self.label_14.setBuddy(self.input_iva)
        self.label_15.setBuddy(self.input_cliente)
        self.label_17.setBuddy(self.input_cuit)
        self.label_18.setBuddy(self.input_ingBrutos)
        self.label_19.setBuddy(self.input_nroRemito)
        self.label_20.setBuddy(self.input_condVenta)

        self.retranslateUi(TicketFactura)
        QtCore.QMetaObject.connectSlotsByName(TicketFactura)
        TicketFactura.setTabOrder(self.input_nroTicket, self.input_fecha)
        TicketFactura.setTabOrder(self.input_fecha, self.input_cliente)
        TicketFactura.setTabOrder(self.input_cliente, self.input_domicilio)
        TicketFactura.setTabOrder(self.input_domicilio, self.input_iva)
        TicketFactura.setTabOrder(self.input_iva, self.input_cuit)
        TicketFactura.setTabOrder(self.input_cuit, self.input_condVenta)
        TicketFactura.setTabOrder(self.input_condVenta, self.input_ingBrutos)
        TicketFactura.setTabOrder(self.input_ingBrutos, self.input_nroRemito)

    def retranslateUi(self, TicketFactura):
        _translate = QtCore.QCoreApplication.translate
        TicketFactura.setWindowTitle(_translate("TicketFactura", "Ticket Factura"))
        self.label.setText(_translate("TicketFactura", "C"))
        self.label_2.setText(_translate("TicketFactura", "FACTURA"))
        self.label_3.setText(_translate("TicketFactura", "N° 0002 - "))
        self.label_4.setText(_translate("TicketFactura", "0000000"))
        self.label_5.setText(_translate("TicketFactura", "FECHA:"))
        self.label_7.setText(_translate("TicketFactura", "Artículos Escolares y Comerciales"))
        self.label_6.setText(_translate("TicketFactura", "La libreria más antigua de Bialet Massé"))
        self.label_8.setText(_translate("TicketFactura", "TWEETY"))
        self.label_9.setText(_translate("TicketFactura", "Fotocopias - Plastificados -  Anillado"))
        self.label_10.setText(_translate("TicketFactura", "de PEÑA DANIEL ALBERTO"))
        self.label_11.setText(_translate("TicketFactura", "ROQUE S. PEÑA 203 - Loc. A - (03543) 155 31652"))
        self.label_12.setText(_translate("TicketFactura", "5158 BIALET MASSE - CORDOBA"))
        self.label_13.setText(_translate("TicketFactura", "RESPONSABLE MONOTRIBUTO"))
        self.label_14.setText(_translate("TicketFactura", "IVA:"))
        self.label_15.setText(_translate("TicketFactura", "Señor(es):"))
        self.label_16.setText(_translate("TicketFactura", "Domicilio:"))
        self.label_17.setText(_translate("TicketFactura", "C.U.I.T:"))
        self.label_18.setText(_translate("TicketFactura", "Ing. Brutos:"))
        self.label_19.setText(_translate("TicketFactura", "Remito N°:"))
        self.label_20.setText(_translate("TicketFactura", "CONDICIONES "))
        self.label_21.setText(_translate("TicketFactura", "DE VENTA"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("TicketFactura", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("TicketFactura", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("TicketFactura", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("TicketFactura", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("TicketFactura", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("TicketFactura", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("TicketFactura", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("TicketFactura", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("TicketFactura", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TicketFactura", "CANTIDAD"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TicketFactura", "DETALLE"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TicketFactura", "P.UNIT"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TicketFactura", "SUBTOTAL"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_22.setText(_translate("TicketFactura", "Nro:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TicketFactura = QtWidgets.QWidget()
    ui = Ui_TicketFactura()
    ui.setupUi(TicketFactura)
    TicketFactura.show()
    sys.exit(app.exec_())
